### ISSUE TITLE
Issue with Forgot Password

### ISSUE THREAD

**Issue by esperanzaua** [Brandply/publicissues#10]
Details
Platform: PC Windows XP
Browswer: Mozilla Firefox
URL of page: https://archer.brandplydev.com/
Organization or Member Login
User: archer
Password: 1234567
Description of Problem: 
Problem with "Forgot Password" link page
1. In Login screen click ""Forgot password"" > bug - ""Login"" screen covering ""Restore your password"" link page. only after click ""Login"" screen hidden.
2. Entering valid username > click ""Submit"" lead to the begining of ""Restore your password"" link page.
3. No option to restore password by e-mail or no function to restore account if forgot username"

Screenshots of Problem:
![_1_bmp](https://cloud.githubusercontent.com/assets/13663282/9135222/d7fd7b9a-3d13-11e5-8392-8e5a809d7eb7.gif)
![fp_1](https://cloud.githubusercontent.com/assets/13663282/9135223/d8e32974-3d13-11e5-831b-d01febf7176d.gif)

**Comment by pfelsted** [comment]
This issue was moved to Brandply/brandply1-1#98
