### ISSUE TITLE
Car Rental category is redirecting to brandply.travel.com

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#100]
Platform: Windows
Browser: Chrome, Firefox, Edge
URL of page: https://archer.brandplydev.com
Organization or Member Login
User: archer
Password: 1234567
Description of Problem:

Car Rental category is redirecting to brandply.travel.com. I could not find any car rental service there thats why im reporting.

Here are the steps that reproduce the problem:
1) Go to archer.brandplydev.com in your browser
2) Log into Archer site u:archer p:1234567
3) Click on Visit Page
4) Open Care Retnal category from mainpage or from Main Categories window

**Comment by brandplysreese** [comment]
there are a few of the main categories that we are linking to the travel site. this is okay.
