### ISSUE TITLE
1-800-Got-Junk? merchant is not displayed under Merchants tab

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#101]
Platform: Windows
Browser: Chrome, Firefox
URL of page: https://archer.brandplydev.com
Organization or Member Login
User: archer
Password: 1234567
Description of Problem:

1-800-Got-Junk merchant is not displayed under Merchants tab, it is visible
in Search window but offer is not loading when opening it under "Locations"

Here are the steps that reproduce the problem:
1) Go to archer.brandplydev.com in your browser
2) Log into Archer site u:archer p:1234567
3) Got to Visit Page
4) Open Merchants and look for 1-800-Got-Junk? merchant.
5) Type 1-800-Got-Junk? in Search window choose first and open it.

**Comment by brandplysreese** [comment]
this is because we are excluding that merchant in the org admin.
