### ISSUE TITLE
Search Window problems

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#102]
Platform: Windows
Browser: Chrome, Firefox, Edge
URL of page: https://brandply.com
Organization or Member Login
User: archer
Password: 1234567
Description of Problem:

Search window can't see offers with space or numbers in name.
For example Cedar Hills Golf Club offer is not displayed in search window when typed correctly.
Its only shown when typed "CedarHills"

Here are the steps that reproduce the problem:
1) Go to brandply.com in your browser
2) Log into Archer site u:archer p:1234567
3) Got to Visit Page
4) Type in search window "Cedar Hills Golf Club" (can't find offer)
5) Type in search window "Cedar" (can't find offer)
6) Type in search window " CedarHills" (offer is displayed)

**Comment by brandplysreese** [comment]
this is an issue with api and they have been made aware
