### ISSUE TITLE
When selecting a location for an offer when i select it does nothing

### ISSUE THREAD

**Issue by pfelsted** [Brandply/publicissues#105]
To select a new address or location you have to select the item then hit the X for it to select.  Once it has been selected it should close the drop down and perform the search

**Comment by brandplysreese** [comment]
As far as I can tell this is native functionality for all selects on iphones. Visit this link in your phone, it will act the same:
http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

I tried a few different sites and they all functioned the same.
