### ISSUE TITLE
Opening offer in new tab or new window is reseting page 

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#107]
Platform: Windows
Browser: Chrome, Firefox, Edge
URL of page: https://brandply.com
Organization or Member Login
User: archer
Password: 1234567
Description of Problem:

Opening in new Tab is opening page reseted to Brandply.com in specific cases:
Opening Category from MainPage
Opening Category from Main Categories menu
Opening Offer when offers view is set to list

Here are the steps that reproduce the problem:
1) Go to brandply.com in your browser
2) Log into Archer site u:archer p:1234567
3) Got to Visit Page
4) Right click on Category from Main Page or Main Categories list and open in new tab
5) Open Category set offer view on List, right click on offer and open in new tab

**Comment by brandplysreese** [comment]
couldnt reproduce issue

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#392
