### ISSUE TITLE
Problem with display on IE11

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#108]
Platform: Windows10, Windows 8.1, Windows 7
Browser: IE11
URL of page: https://archer.brandplydev.com
Organization or Member Login
User: archer
Password: 1234567
Description of Problem:

IE11 have problem with displaying some content

<img width="928" alt="ie11 display" src="https://cloud.githubusercontent.com/assets/13362917/11213059/3771e3f6-8d3a-11e5-935e-a25f514d4034.png">

there is screen how it looks normally 
<img width="437" alt="chromedisplay" src="https://cloud.githubusercontent.com/assets/13362917/11213066/43cc803e-8d3a-11e5-8629-16ce14582012.png">

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#226
