### ISSUE TITLE
Password parameters

### ISSUE THREAD

**Issue by AshleyBeresh** [Brandply/publicissues#11]
When creating a new profile (activating a new account) there are no parameters listed (i.e. how many characters, capitalized letters or numbers needed) to create a successful password. 
URL of page(s): All home pages (when logged out)
Organization or Member Login: Both
![screen shot 2015-08-07 at 11 11 54 am](https://cloud.githubusercontent.com/assets/13679167/9138920/def5b1ca-3cf4-11e5-8fd8-65f2bc550f43.png)

**Comment by pfelsted** [comment]
PRB to decide requirements

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply1-1#113
