### ISSUE TITLE
Offer stuck on loading when open from merchant page

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#111]
Platform: Windows 10, Windows 7
Browser: Chrome, Firefox, Edge
URL of page: https://archer.brandplydev.com
Organization or Member Login
User: archer
Password: 1234567
Description of Problem:

When opening an offer (described as address under locations map) choosen directly from merchant page the page stuck on loading. Location pointers on map are not opening offers as well 

Here are the steps that reproduce the problem:
1) Go to archer.brandplydev.com in your browser
2) Log into Archer site u:archer p:1234567
3) Got to Visit Page
4) Click on Merchants
5) Open 24 Hour Fitness merchant
6) Click on any store displayed under map to open offer
+
7) Click on pointer displayed on map to open offer

**Comment by brandplysreese** [comment]
fixed in todays deploy
