### ISSUE TITLE
Can't open offers on IPhone and Android

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#112]
Platform: IOS, IPhone 6, Phone 6 Plus
Browser: Safari
URL of page: https://archer.brandplydev.com
Organization or Member Login
User: archer
Password: 1234567
Description of Problem:

When choosing an offer for specified location there is only option to get reedem coupon,
can't read whole offer description or open it to see all details (like location etc)

Here are the steps that reproduce the problem:
1) Go to archer.brandplydev.com on your phone
2) Log into Archer site u:archer p:1234567
3) Got to Visit Page
4) Open Dining & Food category
5) Set ZipCode 84062 and click on Restaurant.com offfer
6) Choose any location and try to open offer

<img width="228" alt="ios offer display issue" src="https://cloud.githubusercontent.com/assets/13362917/11276084/dfe33416-8ee0-11e5-9bc2-cd7d55476b92.png">

**Comment by brandplysreese** [comment]
fixed in todays deploy, we added the full offer text when clicking the redeem type.
