### ISSUE TITLE
Inproper dropdown behavior on Admin Dashboard for IOS and Android

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#114]
Platform: IOS, Android
Browser: Safari
URL of page: https://archer.brandplydev.com
Organization or Member Login
User: archer
Password: 1234567
Description of Problem:

When on Admin Dashboard with dropdown menu open, and scrolling down page the menu dont stay on top of screen like login or dropdown on Visit Site but its scrolling with rest of page

Here are the steps that reproduce the problem:
1) Go to archer.brandplydev.com on your phone
2) Log into Archer site u:archer p:1234567
3) Open Dropdown and scroll page down

<img width="190" alt="dropdown list3" src="https://cloud.githubusercontent.com/assets/13362917/11308543/2494693e-8fbf-11e5-9fb0-dfc1b072ea0b.png">
<img width="188" alt="dropdown list4" src="https://cloud.githubusercontent.com/assets/13362917/11308550/2a2eb6d8-8fbf-11e5-94eb-7b906740b008.png">

**Comment by brandplysreese** [comment]
this has been fixed in todays deploy
