### ISSUE TITLE
Inproper display for SONIC offer when open from Search tab

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#116]
Platform: IOS, Android, Windows
Browser: Safari
URL of page: https://archer.brandply.com
Organization or Member Login
User: archer
Password: 1234567
Description of Problem:

When typing SONIC in search tab and chosing first link there is bug in display

<img width="659" alt="sonic1" src="https://cloud.githubusercontent.com/assets/13362917/11339201/b4a3d34e-91f8-11e5-89cf-89fa75032429.png">

<img width="658" alt="sonic display" src="https://cloud.githubusercontent.com/assets/13362917/11339202/b5da1002-91f8-11e5-87a8-a54a3b7ffe17.png">

**Comment by brandplysreese** [comment]
this has been fixed in todays deploy
