### ISSUE TITLE
"How it Works" Section

### ISSUE THREAD

**Issue by AshleyBeresh** [Brandply/publicissues#12]
How it works section should disappear once logged in to any organization's home screen. Also, copy under the "1.Click the “Get Started” button below to go to the sign up page." should be removed - it is no longer accurate.
URL of page(s): All organizations home pages (when logged in)
Organization or Member Login: Both
![screen shot 2015-08-07 at 11 14 32 am](https://cloud.githubusercontent.com/assets/13679167/9139004/61a05bde-3cf5-11e5-8bab-1f517126258a.png)
![screen shot 2015-08-07 at 11 17 50 am](https://cloud.githubusercontent.com/assets/13679167/9139037/a057a300-3cf5-11e5-8a2d-51e8d900e1fd.png)

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply1-1#112
