### ISSUE TITLE
Submit Organisation button is not wroking

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#125]
Platform: Android, Windows
Browser: Chrome, Edge, Firefox
URL of page: https://archer.brandply.com
Organization or Member Login
User: superarcher
Password: 1234567
Description of Problem:

When clicking on Submit Organisation button the changes are not saved and page is not refreshing.

Here are the steps that reproduce the problem:
1) Go to archer.brandply.com in your browser
2) Log into Archer site u:superarcher p:1234567
3) Click on Organizations and choose Add Organization
4) Do some changes (exclude one merchant for egzample)
5) Click on Submit Organisation
6) Check if page is refreshing
7) Check if changes are saved on the site

**Comment by brandplysreese** [comment]
this has been fixed directly on master and will be  merged back into dev.

**Comment by pfr1990** [comment]
Problem is repeating for brandplystaging.com

**Comment by brandplysreese** [comment]
I havent been able to re create this on brandplystaging.com with the superarcher user. I tried Chrome latest in windows 10 and it worked fine. Any specific versions of windows or chrome?

**Comment by pfr1990** [comment]
If filling Display Name, Organization Subdomain and Company Website fields the button is working
anyway there is no option like before just to exclude some merchants or categoreis from site just by clicking on exclude and accepting by Submit Organization button. So I think feature is working but you cant exclude from site.
