### ISSUE TITLE
Redeem Via link is not working for some offers

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#126]
Platform: All
Browser: Chrome, Edge, Firefox
URL of page: https://brandply.com
Organization or Member Login
User: superarcher
Password: 1234567
Description of Problem:

When clicking on Redeem Via link for offers what redirecting to reedem page using https://www.memberweb.com site there is blank page with message: 
"Sorry, there was a problem with your request."

Applebee's reedem address when using Reedem Via Link: https://www.memberweb.com/FIPOffers/Applebees/Applebees.asp?programidentifier=191

Men's Wearhouse reedem address when using Reedem Via Link: 
https://www.memberweb.com/FIPOffers/mensWH/mensWH.asp?programIdentifier=191

Costco reedem address when using Reedem Via Link: 
https://www.memberweb.com/FIPOffers/costco/costco.asp?programidentifier=191

Here are the steps that reproduce the problem:
1) Go to archer.brandply.com in your browser
2) Log into Brandply site u:archer p:1234567
3) Open Dining & Food category from main page
4) Set ZipCode on 84062
5) Open Applebee's offer and click on Redeem Via link
6) Check Terms And Conditions
7) Click on Reedeem Coupon link

**Comment by brandplysreese** [comment]
i created an issue for the raw html in terms and conditions. the broken redeem link is the whats being returned from the API. i will notify them about the links.

**Comment by brandplysreese** [comment]
this has been moved to brandply issues

**Comment by brandplysreese** [comment]
this is something only the api provider can fix, i will remind them of the issue.
