### ISSUE TITLE
No "back to top" button for Admin Dashboard for Android and IOS

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#127]
Platform: All
Browser: Chrome, Safari, Edge
URL of page: https://brandplystaging.com
Organization or Member Login
User: superarcher
Password: 1234567
Description of Problem:

There is no back to top button for Admin Dashboard

Here are the steps that reproduce the problem:
1) Go to brandplystaging.com in your browser
2) Log into Brandply site u:superarcher p:1234567
3) Scroll down to the end of page to see if there is back to top button
4) Open Edit Organisation, and repeat step 3)

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#333
