### ISSUE TITLE
Load More button issue

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#129]
Platform: Windows
Browser: All
URL of page: https://brandply.com
Organization or Member Login
User: archer
Password: 1234567
Description of Problem:

When displaing offers and clicking on Load More button untill all are displayed, then using Sort from filter, offers dissapearing.

Here are the steps that reproduce the problem:
1) Go to https://brandply.com in your browser
2) Enter ZipCode when propted: 84062
2) Log into Archer site u:archer p:1234567
3) Click on Ski & snowboard category
4) Scroll down and click on Load More button to display more offers
5) Repeat untill all offers are displayed
6) Click on Filter, set up any sort options and click on Sort

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#318

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#335
