### ISSUE TITLE
Main Categories content is dissapearing

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#13]
Platform: Pc Windows 10
 Browser: Microsoft Edge
 URL of page: https://archer.brandplydev.com/
 Organization or Member Login
 User: archer
 Password: 1234567
 Description of Problem: 

After expanding Main Categories content and mouse right clicking on the subcategory or blank space
the whole categories area is dissapearing.

Here are the steps that reproduce the problem:
![image](https://cloud.githubusercontent.com/assets/13362917/9141393/9bf7a4de-3d38-11e5-874e-b0d1b4fbaa14.png)

Video (not public): https://www.youtube.com/watch?v=1edIIoLDmyA&feature=youtu.be

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply1-1#111
