### ISSUE TITLE
Location better display

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#133]
Lots of offers are displayed on web map incorectly. The display is dependend from ZipCode instead of full offer address, what means locations are showed on same spot for different offers,

This is incorrect location, common for many offers with ZipCode 84062 
<img width="695" alt="5 buck" src="https://cloud.githubusercontent.com/assets/13362917/11543770/c51bd774-993e-11e5-9e3c-5004c0b889d1.png">

Each offer have its own address wich is actually link to google maps with more detailed location:
<img width="664" alt="real address" src="https://cloud.githubusercontent.com/assets/13362917/11544344/afe9e0e6-9941-11e5-973a-0070af60b70d.png">

<img width="699" alt="real loc" src="https://cloud.githubusercontent.com/assets/13362917/11544354/bcb8f4ec-9941-11e5-90ae-44423abe827b.png">

I think website could use info stored under offer address to get better display.

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#300
