### ISSUE TITLE
Editing stars on Safari open Offers/Categories instead

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#134]
Platform: OSX Snow Leopard, OSX Lion
Browser: Safari
URL of page: https://archer.brandply.com
Organization or Member Login
User: archer
Password: 1234567
Description of Problem:

When trying to favorite category, by clicking on star the page is opening category instead.
Editing star displayed on offers is opening offer.

Here are the steps that reproduce the problem:
1) Go to archer.brandply.com in your browser
2) Log into Archer site u:archer p:1234567
3) Scroll down to categories and click on a star to change its color
4) Open offers list and click on star

**Comment by pfelsted** [comment]
works fine on release 12/23/2015 release staging 1.2.5 - please regression test piotr
