### ISSUE TITLE
My Favourite Offers issues.

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#135]
My Favourite Offers are displayed without info about address, if there are two or more same offers favorited for different locations, user wont know which one to open. When clicking on arrow on the right there is no dropdown with location but page is opening offer instead. Also when clicking on star, offer dissapearing what can be problem if clicking on wrong one by mistake.

<img width="586" alt="favorite offers" src="https://cloud.githubusercontent.com/assets/13362917/11587452/dcab6d46-9a79-11e5-84a8-7d99933574fa.png">

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#317
