### ISSUE TITLE
Filter display issue

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#137]
When opening filter on main page for the first time after login there is different display than after refresh.
Also distance slider should display "2000 mi" at the end of slider.

There are steps to reproduce the problem:
1) Open archer.brandply.com in your browser
2) Log into site   u: archer  p:1234567
3) Open filter on mainpage
4) Refresh page, open filter again and compare

When opening after login:
<img width="874" alt="filter" src="https://cloud.githubusercontent.com/assets/13362917/11594368/e353aa16-9aa9-11e5-9dcf-17f910d24e42.png">

<img width="878" alt="filter2" src="https://cloud.githubusercontent.com/assets/13362917/11594370/e74484ba-9aa9-11e5-980e-3773931bb333.png">

After page is refreshed:
<img width="874" alt="filter after refresh" src="https://cloud.githubusercontent.com/assets/13362917/11594379/ef497706-9aa9-11e5-889d-1d5e0cde7e18.png">

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#261
