### ISSUE TITLE
Find Deals in Your Area / Filter issue when location alert ignored

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#139]
After opening site the location web build alert prompts up asking if I want to share my PC location or to block this function:

<img width="425" alt="location window firefox" src="https://cloud.githubusercontent.com/assets/13362917/11868879/506b456c-a4bb-11e5-8918-6e5a325525d5.png"><img width="378" alt="chrome loaction" src="https://cloud.githubusercontent.com/assets/13362917/11868880/5223a246-a4bb-11e5-9447-b0d931525533.png">
<img width="756" alt="location ie" src="https://cloud.githubusercontent.com/assets/13362917/11868882/55bbd8ce-a4bb-11e5-8fb3-54c7f5bda00a.png">

If you ignore this alert and not choose to allow or block, the site cant display offers using "Find Deals in Your Area" or search by ZipCode from Filter.

(When alert is ignored)
<img width="871" alt="archer-zipcode denied" src="https://cloud.githubusercontent.com/assets/13362917/11868959/fea2c128-a4bb-11e5-99ea-f3a0a8e1f23c.png">

(When alert is not ignored)
<img width="870" alt="archer-zipcode with prompt" src="https://cloud.githubusercontent.com/assets/13362917/11868981/1756e140-a4bc-11e5-9b5d-9eaaf4853ff3.png">

Right now there is no way to handle this alerts in automation testings using Selenium and there is no walkaround so all tests are failing when trying to find offer using ZipCode.
Can you change page display so there will be always option to search for offers using "Find Deals in Your Area" or by using Filter even if alert is ignored?

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#284

**Comment by brandplysreese** [comment]
@pfr1990 this is the correct functionality https://www.dropbox.com/s/znybxe8971a6ehk/Screen%20Capture%202015-12-18%20at%2012.01.33.mov?dl=0

if a user or Selenium ignores the browser location alert, the site treats it as if the user clicked disallow and should show the zipcode inputs for manually entering location.
