### ISSUE TITLE
Repo - mobile app drop down too big

### ISSUE THREAD

**Issue by pfelsted** [Brandply/publicissues#14]
We need to try and reproduce and add more details.
Customer: Levine Shosh iheartmedia

When you use the mobile app and re-log in, the screen is taken over with the drop down and you can’t see the offers (the red 3 bar hot dog button disappears

**Comment by brandplysreese** [comment]
Short Description (Title):

When a user logs in to an org on mobile devices(iphone and ipad tested) the login popup/dropdown doesnt close. On ipad the main nav menus are open and some are hidden.

Details
Platform: ios 8
Browser: mobile safari, chrome mobile
URL of page(s): https://archer.brandplydev.com/
Organization or Member Login
User: sarcher
Password (only add passwords of test accounts): 1234567

Description of Issue (steps to reproduce):

Visit https://archer.brandplydev.com on an iphone or ipad.
Login with credentials from above.

The issues can be created with chromes mobile dev tools when inspecting element if you dont have actual devices.

Screenshots or screen casts of Issue:

![img_3282](https://cloud.githubusercontent.com/assets/12085564/9188359/5465a68e-3fa9-11e5-88fb-1ba69fbfc6bd.PNG)
![img_0005](https://cloud.githubusercontent.com/assets/12085564/9188364/64bf5c46-3fa9-11e5-8406-0891c10ee680.PNG)
![img_0008](https://cloud.githubusercontent.com/assets/12085564/9188367/758a91bc-3fa9-11e5-8a6c-84691256b55b.PNG)

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply1-1#103
