### ISSUE TITLE
Clicking on Admin Dashboard form header redirecting to wrong address.

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#140]
Platform: Windows
URL of page: https://brandplystaging.com
Organization or Member Login
User: superarcher
Password: 1234567
Description of Problem:

When clicking on Admin Dashboard from header, the page is redirecting to https://brandply.com instead of https://brandplystaging.com/admin/dashboard. The admin dashboard can be opened only when loggin in as admin so its opening first.

Here are the steps that reproduce the problem:
1) Go to https://brandplystaging.com in your browser
2) Log into Archer site u:superarcher p:1234567
3) Click View Site
4) Click on Admin Dashboard
5) Check if page is redirecting correctly

**Comment by brandplysreese** [comment]
fixed
