### ISSUE TITLE
Bad visibility for "Load More" and "Sort" buttons

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#142]
Load More and Sort buttons visiblitity is ok for Chrome but its hard to see in other browsers, escpecially on bright screen.

<img width="520" alt="visibility" src="https://cloud.githubusercontent.com/assets/13362917/11896604/4150437a-a588-11e5-867e-632f11a711e0.png">

**Comment by pfelsted** [comment]
This is a feature chagne.  We will need to allow users to specify text color, black or white.

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#298
