### ISSUE TITLE
Offers sorted by ZipCode are displayed in different order for every browser

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#143]
Offers are displayed in different order for Chrome, Firefox and Edge/IE (same display for these)

Here are the steps that reproduce the problem:
1) Go to https://brandplystaging.com in your browser
2) Log into Archer site u:archer p:1234567
3) Open Automotive category
4) Repeat steps for two different browsers and compare displayed offers

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#297
