### ISSUE TITLE
Clicking on offer image from Popular view redirecting to /merchant

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#144]
Here are steps to reproduce the problem:
1) Open https://brandplystaging.com in your browser
2) Enter ZipCode when prompted: 84062
3) Log into site u: archer p:1234567
4) Click on Popular tab on header
5) Set offers view to large pictures
6) Click on Logo picture

<img width="503" alt="popular" src="https://cloud.githubusercontent.com/assets/13362917/11897293/c95a77ee-a58e-11e5-9ff1-f92e54f88640.png">

After clicking page is redirecting to https://brandplystaginng.com/merchant/

<img width="660" alt="popular-merchant" src="https://cloud.githubusercontent.com/assets/13362917/11897300/d9991728-a58e-11e5-9961-d51fe7c73b91.png">

**Comment by brandplysreese** [comment]
moved to brandply issues
