### ISSUE TITLE
Choosing subcategory from Main Categories display same offers 

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#145]
When opening Main Categories window and choosing different subcategories the offers are not sorted but displayed like for normal category.

Here are steps to reproduce the problem:
1) Open https://brandplystaging.com in your browser
2) Enter ZipCode when prompted: 84062
3) Log into site u: archer p:1234567
4) Click on Main Categories window
5) Select Automotive category and open different subcategories from tree on the right side

The displayed offers are same like when clicking directly on Automotive

**Comment by brandplysreese** [comment]
moved over to brandply issues
