### ISSUE TITLE
Can't favorite Categories on admin account

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#146]
Platform:  Windows
Browser: Chrome, Edge, Firefox, IE, Safari
URL of page: https://brandplystaging.com
Organization or Member Login
User: superarcher
Password: 1234567
Description of Problem:

When logged as superarcher, the stars displayed on categories are not editable (works if logged as archer).

Here are the steps that reproduce the problem:
1) Go to brandplystaging.com in your browser
2) Log into site u:superarcher p:1234567
3) Click on Visit Site
4) Scroll down to categories and try to edit star color

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#296
