### ISSUE TITLE
IOS - When opening page, location window is sometimes prompting twice

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#147]
Platform: IOS
Browser: Safari
URL of page: https://brandplystaging.com
Organization or Member Login
User: superarcher
Password: 1234567
Description of Problem:

On IOS the location window is always prompting when page is open, if there is also an alert asking to Allow or Deny physical location, when clicking on Deny location window is prompting second time

**Comment by brandplysreese** [comment]
i couldnt recreate this on safari on my iphone.
