### ISSUE TITLE
IOS Main Categories dropdown sometimes is not showing Categories after click

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#148]
Platform: IOS
Browser: Safari
URL of page: https://brandplystaging.com
Organization or Member Login
User: superarcher
Password: 1234567
Description of Problem:

When clicking on Main Categories menu sometimes its not showing its content. Because its happening only sometimes it might be browserstack issue.

Before Click: 

<img width="278" alt="before click" src="https://cloud.githubusercontent.com/assets/13362917/12018797/10a0e724-ad68-11e5-8b40-79c06ef1ced3.png">

---

After Click:

<img width="278" alt="after click" src="https://cloud.githubusercontent.com/assets/13362917/12018772/d9cf526c-ad67-11e5-8ea8-b56a5d73cd6d.png">

**Comment by brandplysreese** [comment]
not able to recreate on safari on my iphone. must be browserstack issue
