### ISSUE TITLE
Favorite categories issue

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#149]
Platform: All
Browser: Edge, Chrome, Safari, Firefox
URL of page: https://brandplystaging.com
Organization or Member Login
User: superarcher
Password: 1234567
Description of Problem:

When favoriting a category on Main Page and refreshing, star color are not saved.

Here are the steps that reproduce the problem:
1) Go to https://brandplystaging.com in your browser
2) Enter ZipCode when propted: 84062
2) Log into Archer site u:archer p:1234567
3) Favorite any Category on main page
4) Refresh page
5) Set favorited category star on red color and refresh
6) Check if star is red

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#303

**Comment by brandplysreese** [comment]
this worked for me
