### ISSUE TITLE
usernames and passwords not working on some mobile devices

### ISSUE THREAD

**Issue by pfelsted** [Brandply/publicissues#15]
We need to reproduce and add more details
Customer: Levine Shosh iheartmedia

·         The user & passwords that were given out cannot also be used on other mobile devices (some tried to use on their tablets after, however were unable to login using their user / pass)

**Comment by brandplysreese** [comment]
#### I created a new account via my iphone 6 with no issues.

 ![img_3278](https://cloud.githubusercontent.com/assets/12085564/9188094/3b353d8a-3fa6-11e5-819c-24d59aa63610.PNG)
 ![img_3279](https://cloud.githubusercontent.com/assets/12085564/9188096/458cf566-3fa6-11e5-9671-09b4966fcc13.PNG)

#### I logged out and back in with no issues.

 ![img_3280](https://cloud.githubusercontent.com/assets/12085564/9188100/62430c22-3fa6-11e5-86d4-2514ca9f20df.PNG)
 ![img_3281](https://cloud.githubusercontent.com/assets/12085564/9188103/69449554-3fa6-11e5-9bee-f3e1eddca33c.PNG)

#### I visited the same site using an iPad running iOS 8.1 and logged in with no problem. There are some css issues and menus that arent collapsing but I logged in with no issue. I will make the menu problems a separate issue in milestone 6.

 ![img_0005](https://cloud.githubusercontent.com/assets/12085564/9188121/85885160-3fa6-11e5-9641-2f19f2041cab.PNG)
 ![img_0006](https://cloud.githubusercontent.com/assets/12085564/9188122/8d4ce2da-3fa6-11e5-9f82-3770af364234.PNG)
 ![img_0008](https://cloud.githubusercontent.com/assets/12085564/9188126/95b44986-3fa6-11e5-9bb1-91eb82c99f9f.PNG)

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply1-1#110
