### ISSUE TITLE
Edge - Edited Organisation is not saving

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#150]
Platform: Windows 10
Browser: Edge
URL of page: https://brandplystaging.com
Organization or Member Login
User: superarcher
Password: 1234567
Description of Problem:

Adding org is working but cannot edit on Edge

Here are the steps that reproduce the problem:
1) Go to https://brandplystaging.com in your browser
2) Enter ZipCode when propted: 84062
2) Log into Archer site u:superarcher p:1234567
3) Click on Organisations from Admin Dashboard and select View Organisations
4) Choose one organisation and change any text
5) Click on submit (page is reseting and showing data before it was edited)

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#304
