### ISSUE TITLE
Wrong locations display for merchants

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#151]
Platform: All
Browser: All
URL of page: https://brandplystaging.com
Organization or Member Login
User: archer
Password: 1234567
Description of Problem:

Displaying merchant (from search window) is showing not updated wrong location on the map.

https://brandplystaging.com/offer/14308632 - good display
https://brandplystaging.com/merchant/19020807 - wrong display

There are steps to reproduce the problem
1) Go into brandplystaging.com
2) Enter ZipCode :84062
3) Log into site  u: archer  p:1234567
4) Click on Golf category and open Cedar Hills Golf Club offer - check location
5) Type in search window "CedarHills" and click on Cedar Hills Golf Club - compare displayed location

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#306
