### ISSUE TITLE
Locations type links are not working in Search option

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#152]
Platform: All
Browser: All
URL of page: https://brandplystaging.com
Organization or Member Login
User: archer
Password: 1234567
Description of Problem:

Locations are not opening from Search window

There are steps to reproduce the problem
1) Go into brandplystaging.com
2) Enter ZipCode :84062
3) Log into site u: archer p:1234567
4) Type in search window "ski" and click on links under "Locations" type

<img width="876" alt="locations" src="https://cloud.githubusercontent.com/assets/13362917/12037363/90b61790-ae4e-11e5-9547-324e7f3eaddc.png">

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#305
