### ISSUE TITLE
Find Deals in Your Area is not working when using Filter

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#154]
Platform: All
Browser: Chrome, Edge, Safari
URL of page: https://brandplystaging.com
Organization or Member Login
User: superarcher
Password: 1234567
Description of Problem:

Entering ZipCode in Find Deals in Your Area window displays offers untill changing any option inside Filter.
Offers wont be displayed untill clicking on Reset Sort.

https://www.youtube.com/watch?v=bgiAqKjDiwM&feature=youtu.be

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#311
