### ISSUE TITLE
Remember Me checkbox not reacting on click

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#155]
Platform: All
Browser: Chrome, Firefox, Edge
URL of page: https://brandply.com
Organization or Member Login
User: superarcher
Password: 1234567
Description of Problem:

When clicking on  Remember the last username I logged in with checkbox on brandply it remains not marked.

Here are the steps that reproduce the problem:
1) Go to https://brandply.com in your browser
2) Click on Login and Remeber the last username i logged in checkbox

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#314
