### ISSUE TITLE
Video on Consumers site is not working

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#156]
Platform: All
Browser: All
URL of page: https://brandply.com
Organization or Member Login
User: superarcher
Password: 1234567
Description of Problem:

Video placed on https://brandplystaging.com/consumers no longer exists, but there is still youtube window.

Here are the steps that reproduce the problem:
1) Go to https://brandply.com in your browser
2) Log into Archer site u:archer p:1234567
3) Scroll down and click on Consumers at Footer
4) Click on video.

**Comment by brandplysreese** [comment]
we havent update the embed code in the admin, but the update was made on live server. this is okay cause only we see the staging server.
