### ISSUE TITLE
Stars on offers have different colors for windows and mobiles and changes are not saving

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#158]
Platform: All
Browser: Chrome, Firefox, Edge, Safari
URL of page: https://brandply.com
Organization or Member Login
User: superarcher
Password: 1234567
Description of Problem:

Stars on IOS and Android can be changed from gray to yellow and yellow to gray and on Windows form gray to red and red to gray. While refreshing after editing colors changes are not saving.

**Comment by brandplysreese** [comment]
created issue in brandply issues
