### ISSUE TITLE
Search window on IOS is not showing hints when typing

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#161]
Platform: IOS - iPhone 6S and iPhone 6S Plus
Browser: Safari
URL of page: https://brandplystaging.com
Organization or Member Login
User: archer
Password: 1234567
Description of Problem:

When typing in search window it should show hints with stores and locations.

Here are the steps that reproduce the problem:
1) Go to https://brandplystaging.com in your browser
2) Enter ZipCode when propted: 84062
2) Log into Archer site u:archer p:1234567
3) Type in Search window "Sonic"
4) Check if hints window is displayed

How it looks on iPhone 6S and iPhone 6S Plus:
<img width="190" alt="search ios" src="https://cloud.githubusercontent.com/assets/13362917/12324883/42165e7c-bac6-11e5-8abf-d1a8da367b14.png">
# 

How should it look like:
<img width="177" alt="search box" src="https://cloud.githubusercontent.com/assets/13362917/12324886/4911916a-bac6-11e5-8553-87fd96abe55e.png">

**Comment by brandplysreese** [comment]
this worked fine on my iphone 6s
