### ISSUE TITLE
Activate button is displayed for IOS and Android after user is logged in

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#162]
Platform: IOS, Android
Browser: Safari, Chrome
URL of page: https://brandplystaging.com
Organization or Member Login
User: archer
Password: 1234567
Description of Problem:

When clicking on options button on main site after logging in there is an Activate button which should be only visible before login.

Here are the steps that reproduce the problem:
1) Go to https://brandplystaging.com in your browser
2) Enter ZipCode when propted: 84062
2) Log into Archer site u:archer p:1234567
3) Click on options menu on the upper right corner

<img width="185" alt="activate" src="https://cloud.githubusercontent.com/assets/13362917/12330083/a4bed0aa-bae3-11e5-82fa-3f53d7534f8d.png">

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#325
