### ISSUE TITLE
Double redeem link for 24 Hour Fitness merchant

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#163]
Platform: All
Browser: Safari, Chrome, Edge
URL of page: https://brandplystaging.com
Organization or Member Login
User: archer
Password: 1234567

Description of Problem:

24 Hour Fitness Merchant have two redeem links when clicking on redeem button.
Firefox is displaying onyl one link.

Here are the steps that reproduce the problem:
1) Go to https://brandplystaging.com in your browser
2) Enter ZipCode when propted: 84062
2) Log into Archer site u:archer p:1234567
3) Open Health & Beauty category
4) Open 24 Hour Fitness offer
5) Click on Redeem Via link and Redeem Coupon button

<img width="195" alt="double redeem link" src="https://cloud.githubusercontent.com/assets/13362917/12330270/9372ec40-bae4-11e5-95f6-ff0891afe02d.png">

**Comment by pfr1990** [comment]
Fixed for phones but still occuring on windwos

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#334
