### ISSUE TITLE
Sorting by Savings on Filter issue

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#164]
Platform: All
Browser: Safari, Chrome, Edge
URL of page: https://brandply.com
Organization or Member Login
User: archer
Password: 1234567

Description of Problem:

Setting Savings on 50% and Discount Type on Percent is not showing all offers containing "50% of discount" in description. 

Here are the steps that reproduce the problem:
1) Go to https://brandply.com in your browser
2) Enter ZipCode when propted: 84003
2) Log into Archer site u:archer p:1234567
3) Open Dining and Food category
4) Open Filter Option and set distance on 180 mi, ZipCode on 84003, Savings on 50% and Discount         __Type on Percent then click on Sort
5) Look for Mi Ranchito Grill offer
Site will show only some offers of with 50% discount

This is screen of offer showed before setting savings on 50%
<img width="729" alt="grill" src="https://cloud.githubusercontent.com/assets/13362917/12330565/21db20d2-bae6-11e5-91e5-e3aa4040de84.png">

<img width="840" alt="filter and results" src="https://cloud.githubusercontent.com/assets/13362917/12330579/2bc8fd3a-bae6-11e5-8ea1-e61d708664fe.png">
After setting filter, cant find Mi Ranchito Grill offer anymore

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#332
