### ISSUE TITLE
IOS - Can't scroll right to see whole organisations pannel

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#165]
Platform: IOS
Browser: Safari
URL of page: https://brandply.com
Organization or Member Login
User: superarcher
Password: 1234567

Description of Problem:

When viewing organizations on admin dashboard, cant scroll right to reach edit/remove options.

1) Go to https://brandply.com in your browser
2) Log into Archer site u:superarcher p:1234567
3) Click on View Organizations
4)Try to scroll right to view more of columns

<img width="211" alt="iphone 6s" src="https://cloud.githubusercontent.com/assets/13362917/12420162/380477fe-bebb-11e5-9a59-1b7edfb5cfe0.png">

**Comment by pfr1990** [comment]
If Organization is search on filter then edit/remove option is accessable

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#331

**Comment by brandplysreese** [comment]
this is working in safari and chrome on my iphone 6s. I tested on staging server, I dont think the fix has made it to the production server yet.

**Comment by brandplysreese** [comment]
Could not recreate this in chrome or safari on iOS.
