### ISSUE TITLE
ZipCode window is accepting wrong format

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#167]
Platform: All
Browser: Safari, Chrome, Edge
URL of page: https://brandplystaging.com
Organization or Member Login
User: archer
Password: 1234567

Description of Problem:

ZipCode window is preventing to accept letters but if first sign is a number then it will accept even if rest of code are letters (for egzample 4ZXCV will pass on Ok button as a ZipCode)

Here are the steps that reproduce the problem:
1) Go to https://brandplystaging.com in your browser
2) Enter ZipCode when prompted: 7qwer (should be blocked by warning)
3) Click on Ok or press enter.

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#349
