### ISSUE TITLE
Search Window dropdown is not working

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#168]
Platform: All
Browser: Chrome, Edge
URL of page: https://brandplystaging.com
Organization or Member Login
User: archer
Password: 1234567

Description of Problem:

Typing in Search not showing dropdown with hints

Here are the steps that reproduce the problem:
1) Go to https://brandplystaging.com in your browser
2) Enter ZipCode when prompted: 84062
3) Type in search window

**Comment by brandplysreese** [comment]
moved to brandply issues
