### ISSUE TITLE
Slow refreshing on Edge

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#169]
Platform: All
Browser:  Edge
URL of page: https://brandplystaging.com
Organization or Member Login
User: archer
Password: 1234567

Description of Problem:

When refreshing page on Edge, the refresh is slow or stuck on white screen

Here are the steps that reproduce the problem:
1) Go to https://brandplystaging.com in your browser
2) Enter ZipCode when prompted: 84062
3) Go to Main Page and refresh

**Comment by brandplysreese** [comment]
I could not recreate this, I tried edge latest on windows 10 following the steps from above.

https://www.dropbox.com/s/t837k0vz6x6kod2/Screen%20Capture%202016-02-02%20at%2011.15.47.mov?dl=0
