### ISSUE TITLE
Search window is not reacting on numbers

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#170]
Platform: All
Browser: All
URL of page: https://brandply.com
Organization or Member Login
User: archer
Password: 1234567

Description of Problem:

Typing in search window numbers is not activating searching.
For example typing 24 will not show 24 Hour Fitness offer untill Hour is not added.

Here are the steps that reproduce the problem:
1) Go to https://brandply.com in your browser
2) Enter ZipCode when prompted: 84062
3) Log into Brandply site
4) Type in search: 24 - search window should show 24 hour fitness offer

**Comment by pfelsted** [comment]
Not a bug this is what the API allows.
