### ISSUE TITLE
Search window is not working for iPhone 6S and iPhone 6S Plus

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#171]
Platform: iPhone 6S, iPhone 6S Plus
Browser: Safari
URL of page: https://brandply.com
Organization or Member Login
User: archer
Password: 1234567

Description of Problem:

Search window showing dropdown with results for iPhone 6S and iPhone 6S Plus

Here are the steps that reproduce the problem:
1) Go to https://brandply.com in your browser
2) Enter ZipCode when prompted: 84062
3) Log into Brandply site u:archer p:1234567
4) Type in search: Golf and see if there is a dropdown with results

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#360
