### ISSUE TITLE
IOS / Android My Favorite Offers redeem via instore bug

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#172]
Platform: IOS, Android
Browser: Safari, Chrome
URL of page: https://brandply.com
Organization or Member Login
User: archer
Password: 1234567

Description of Problem:

Many offers displayed under My Favorite Offers are not showing link to redeem when clicking on Redeem via Instore, it can appear if clicking on Redeem via Instore Print and switching on Redeem via Instore again
# <img width="199" alt="brandply0" src="https://cloud.githubusercontent.com/assets/13362917/12916177/b83a44dc-cf30-11e5-89a2-80b659b4b3a1.png">
# <img width="201" alt="brandply" src="https://cloud.githubusercontent.com/assets/13362917/12916182/bdd7306c-cf30-11e5-91a8-a1902b02ea7f.png">

<img width="196" alt="brandply2" src="https://cloud.githubusercontent.com/assets/13362917/12916186/c17d1cea-cf30-11e5-94d3-5b2e8b3394ae.png">

Here are the steps that reproduce the problem:
1) Go to https://brandply.com in your browser
2) Enter ZipCode when prompted: 84062
3) Log into Brandply site u:archer p:1234567
4) Click on My Favorite Offers
5) Choose some of offers with Redeem via Instore and Redeem via Instore Print and click on Redeem via Instore

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#359
