### ISSUE TITLE
Windows Phone - redeem bug

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#173]
Platform: Windows Phone
Browser: IE
URL of page: https://brandply.com
Organization or Member Login
User: archer
Password: 1234567

Description of Problem:

While clikcing on redeem option on Windows Phone page stucks on loading screen

Here are the steps that reproduce the problem:
1) Go to https://brandply.com in your browser
2) Enter ZipCode when prompted: 84062
3) Log into Brandply site u:archer p:1234567
4) Open any Category and choose an offer
5) Click on Redeem button

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#358
