### ISSUE TITLE
Load More button bug

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#174]
Platform: Windows
Browser: All
URL of page: https://brandply.com
Organization or Member Login
User: archer
Password: 1234567

Description of Problem:

When offers are displayed as list and user click's Load More button untill all offers are loaded, then switching view to display pictures, there are only four offers displayed and Load More button is missing.

https://www.youtube.com/watch?v=M9SUR6eBNJA&feature=youtu.be

Here are the steps that reproduce the problem:
1) Go to https://brandply.com in your browser
2) Enter ZipCode when prompted: 84062
3) Log into Brandply site u:archer p:1234567
4) Open Category Dining & Food
5) Open Filter and set distance on 20 mi
6) Set category view on list
7) Click Load More button untill its dissapear
8) Change view to pictures - load more button is missing

Before loading all offers:
## <img width="840" alt="load more 1" src="https://cloud.githubusercontent.com/assets/13362917/13056032/0804f52a-d413-11e5-80d8-ab5b4004c072.png">

After loading all offers in list view and switching back to pics view
<img width="839" alt="load more 2" src="https://cloud.githubusercontent.com/assets/13362917/13056056/228658e4-d413-11e5-8418-0921a7a8f4cc.png">

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#363
