### ISSUE TITLE
Categories on Main Page are not working for staging

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#176]
Platform: All
Browser: All
URL of page: https://brandplystaging.com
Organization or Member Login
User: archer
Password: 1234567

Description of Problem:

When clicking on a Category on Main Page (which is not a brandplytravel.com link)  , the site is opening new tab with brandplystaging.com address while it should redirect to choosen Category. 

Here are the steps that reproduce the problem:
1) Go to https://brandplystaging.com in your browser
2) Enter ZipCode when prompted: 84062
3) Log into Brandply site
4) Click on Dining&Food category on main page

**Comment by brandplysreese** [comment]
fixed
