### ISSUE TITLE
Signout from Admin Dashboard issue

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#178]
Platform: All
Browser: All
URL of page: https://brandply.com
Organization or Member Login
User: superarcher
Password: 1234567

Description of Problem:
When clicking on Signout button on Admin Dashboard, page is not displayed correctly

Here are the steps that reproduce the problem:
1) Go to https://brandply.com in your browser
2) Enter ZipCode when prompted: 84062
3) Log into Brandply site u: superarcher p:1234567
4) When on Admin Dashboard, click on Signout button

<img width="837" alt="admin signout" src="https://cloud.githubusercontent.com/assets/13362917/14787955/27b69d04-0b06-11e6-94bd-a980596fddc1.png">

**Comment by brandplysreese** [comment]
This is new and is the intended functionality now. There is a new admin login page.
