### ISSUE TITLE
Android Main Categories dropdown bug

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#179]
Platform: Android
Browser: Chrome
URL of page: https://brandplystaging.com
Organization or Member Login
User: superarcher
Password: 1234567

Description of Problem:
Arrows placed on Main Categories dropdown do nothing after click while clicking near to it opens choosen category.
Tested on newest devices.

Here are the steps that reproduce the problem:
1) Go to https://brandplystaging.com in your browser
2) Enter ZipCode when prompted: 84062
3) Log into Brandply site u: superarcher p:1234567
4) Go to Visit Site
5) Open options dropdown and select Main Categories
6) Click on arrow right to category name

![brandply](https://cloud.githubusercontent.com/assets/13362917/15935218/dce7fadc-2e66-11e6-9e49-ee3d031caba1.png)

**Comment by brandplysreese** [comment]
https://github.com/Brandply/brandply/commit/0990e0ef3752d31f5adab42e8bc222c6ef68f447
