### ISSUE TITLE
Repo - maps to big on mobile

### ISSUE THREAD

**Issue by pfelsted** [Brandply/publicissues#18]
We need to try and reproduce and add more details.
Customer: Levine Shosh iheartmedia

The maps take over the screen, and confused ae’s of how they could get down to the actual offer on their phones (can this be shrunk?)

**Comment by brandplysreese** [comment]
Short Description (Title):

Google maps are too big when viewing offers on mobile devices. The map takes up the majority of the screen and has touch enabled which makes it hard for a user to scroll. If we want the devs to anything more than change the height of the map we will need to provide them with a mockup.

Details
Platform: iphone 4,5,6,6+, android devices of similar sizes
Browser: mobile safari, chrome mobile
URL of page(s): https://archer.brandplydev.com/offer/11855843 or when viewing any single offer url
Organization or Member Login
User: sarcher
Password (only add passwords of test accounts): 1234567

Description of Issue (steps to reproduce):

Login and navigate to an offer by clicking the "view offer" button or offer image of any offer.
Scroll down to the map.

Screenshots or screen casts of Issue:
![img_3277](https://cloud.githubusercontent.com/assets/12085564/9187419/1eb095ae-3f9e-11e5-83e6-ab771c3586dd.PNG)

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply1-1#101
