### ISSUE TITLE
iPhone options dropdown bug

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#180]
Platform: IOS
Browser: Safari
Device: iPhone 6S Plus
URL of page: https://brandplycom
Organization or Member Login
User: superarcher
Password: 1234567

Description of Problem:
Sometimes after clicking on Main Categories from options dropdown, content is cut off.
![ios](https://cloud.githubusercontent.com/assets/13362917/16060989/15a8e9d0-328b-11e6-9f5a-4a5ff2d59593.png)
This is happening rarely so it can be hard to reproduce, also might be browserstack bug.

Here are the steps that reproduce the problem:
1) Go to https://brandply.com in your browser
2) Enter ZipCode when prompted: 84062
3) Log into Brandply site u: superarcher p:1234567
4) Go to Visit Site
5) Open options dropdown and select Main Categories

**Comment by brandplysreese** [comment]
Could not create on actual device. This seems to be a browserstack issue.
