### ISSUE TITLE
Windwos 10 split screen display problem

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#181]
Platform: Windows 10
Browser: Edge, Chrome, Firefox
URL of page: https://brandply.com
Organization or Member Login
User: superarcher
Password: 1234567

Description of Problem:
Windows 10 option to split screen is not displaing category pictures on the site

Here are the steps that reproduce the problem:
1) Go to https://brandply.com in your browser on windows 10
2) Enter ZipCode when prompted: 84062
3) Log into Brandply site u: superarcher p:1234567
4) Go to Visit Site
5) Set Categories View to pictures
6) Drag browser to the left or right side of screen to display it on the splitted windows screen
7) Check if categories are displayed

this is the screen of site after splitting windows view
![brandply2](https://cloud.githubusercontent.com/assets/13362917/16283625/d150f68a-38cd-11e6-8dfe-11ae968e3d40.png)

**Comment by pfelsted** [comment]
Not a bug any longer
