### ISSUE TITLE
3 different users view display

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#186]
Platform: All
URL of page: https://brandply.com
Browser: Chrome
Organization or Member Login
User: superarcher
Password: 1234567

Description of Problem:
When opening View Users tab and setting display on "All" the dispaly is getting broken, then after reloading page display is even more differe

Here are the steps that reproduce the problem:
1) Go to https://brandplystaging.com in your browser
2) Enter ZipCode : 84062
3) Log into Brandply site u: superarcher p:1234567
4) On Admin's Page click on Users and View Users tab
5) Set display from "10" to "All" 
6) Reload page

How it looks on the begining :
![users3](https://cloud.githubusercontent.com/assets/13362917/17114275/7323242a-52ae-11e6-98b3-84f7b8b0ee50.png)

How it looks after changing display to "All" :
![users](https://cloud.githubusercontent.com/assets/13362917/17114291/878318e4-52ae-11e6-9d3f-60a5863bec04.png)

How it looks after reloading page:
![users2](https://cloud.githubusercontent.com/assets/13362917/17114294/8f0276c8-52ae-11e6-8516-8c7c6eabc8d8.png)

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#447
