### ISSUE TITLE
IOS dropdown arrows display bug

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#187]
Platform: IOS Iphone 5s (on browserstack)
URL of page: https://brandply.com
Browser: Safari
Organization or Member Login
User: superarcher
Password: 1234567

Description of Problem:
Dropdown arrows are not displaing properly
![brandply -- ios](https://cloud.githubusercontent.com/assets/13362917/17114380/e89778fa-52ae-11e6-8f4f-285a05ecab0e.png)

Here are the steps that reproduce the problem:
1) Go to https://brandply.com in your browser on your browser
2) Enter ZipCode : 84062
3) Log into Brandply site u: superarcher p:1234567
4) Go to Visit Page
5) Choose One Category to display offers

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#448
