### ISSUE TITLE
IOS display bug

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#188]
Platform: IOS Iphone 5s (on browserstack)
URL of page: https://brandply.com
Browser: Safari
Organization or Member Login
User: superarcher
Password: 1234567

Description of Problem:
Some of elements on IOS have strage icons replacing normal ones, they are not allowing to check if category or offer is actualy favorited because of no reaction on click 
![brandply favoriting category](https://cloud.githubusercontent.com/assets/13362917/17114505/7f0de76a-52af-11e6-92fc-08f8b7331429.png)

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#449
