### ISSUE TITLE
Better display for My Favorite Categories on mobile

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#189]
Currently My Favorite Categories display bolded deal at the top of offer, and small offer name at the middle. I belive swapping offer with deal and making name bigger and bolded instead of deal would make display more clear.

![my fav offers display](https://cloud.githubusercontent.com/assets/13362917/17140973/c97ec7d8-534a-11e6-99b7-6cc652c447d9.png)

**Comment by pfelsted** [comment]
Not going to do
