### ISSUE TITLE
logos too big on Mobile

### ISSUE THREAD

**Issue by pfelsted** [Brandply/publicissues#19]
We need to try and reproduce and add more details.
Customer: Levine Shosh iheartmedia

The brandplay logo & bar (which I know will be the clients logo once we sell to the client) is very large and takes up a quarter of the screen - could this be shrunk to the total bottom of the screen to help make more user-friendly?

**Comment by brandplysreese** [comment]
Short Description (Title):

The Footer/Logo take up too much of the screen on mobile. We will need to provide the devs with a mockup of how it should look. 

Details
Platform: iphone 4,5,6,6+, android devices of similar sizes
Browser: mobile safari, chrome mobile.
URL of page(s): https://archer.brandplydev.com/
Organization or Member Login
It happens whether youre logged in or logged out.
User: sarcher
Password (only add passwords of test accounts): 1234567

Description of Issue (steps to reproduce):

Visit https://archer.brandplydev.com/ on a mobile device and start scrolling, the footer will appear and take up a big portion of the screen, making it hard to navigate.

Screenshots or screen casts of Issue:
![img_3276](https://cloud.githubusercontent.com/assets/12085564/9187251/44a69e72-3f9c-11e5-9174-b80cffff8ae2.PNG)

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply1-1#100
