### ISSUE TITLE
ZipCode window is showing up before autolocation option is disabled

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#190]
Platform: All
URL of page: https://brandplystaging.com
Organization or Member Login
User: superarcher
Password: 1234567

Description of Problem:
When opening page for the first time and question about autolocation is prompting up the ZipCode window is showing before autolocation is actually disabled

![zipcode](https://cloud.githubusercontent.com/assets/13362917/17330511/538c9b40-58c7-11e6-8b98-d22c630632f5.png)

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#459
