### ISSUE TITLE
Map pointers are not redirecting on click to google maps (except for Chrome)

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#191]
Platform: All
URL of page: https://brandplycom
Organization or Member Login
User: superarcher
Password: 1234567

Description of Problem:
Map pointers should open new page with google maps location on click, this functionality works only on Chrome and not working on Firefox, Edge and IE

Here are the steps that reproduce the problem:
1) Go to https://brandply.com in your Firefox / Edge / IE browsers
2) Enter ZipCode : 84062
3) Log into Brandply site u: superarcher p:1234567
4) Go to Visit Site
5) Open an offer with location placed on google.maps (for eg. Sonic)
6) Click on map pointer on Offer Location
7) Switch to Other Locations tab and click on map pointer

**Comment by inqueez** [comment]
it is working in Chrome and FF on my desktop, I can't check it in IE or Edge because I am using Linux
