### ISSUE TITLE
Some offers have wrong display location

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#197]
Platform: Windows 10
Browser: Firefox. Chrome
URL of page: https://brandply.com 
Organization or Member Login
User: superarcher
Password: 1234567

Cedar Hills Golf Club offer is an offer with only one location, the "Offer Location" tab is showing wrong location while Other Locations tab (which should not show any location) shows the correct one I noticed the same issue with Cedar Glen Golf Club offer. 

Here are the steps that reproduce the problem:
1) Go to https://brandply.com in your browser
2) Enter ZipCode : 84062
3) Log into Brandply site u: superarcher p:1234567
4) Go to Visit Site
5) Type in search Cedar Hills Golf Club and open an offer
6) Compare Offer Location and Other Locations tab

**Comment by inqueez** [comment]
This issue was moved to Brandply/brandply#534
