### ISSUE TITLE
Archer banner showing bugged popup on click

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#198]
Platform: Windows 10
Browser:  Chrome
URL of page: https://archer.brandplystaging.com 
Organization or Member Login
User: superarcher
Password: 1234567

When clicking on archer banner on the main page there is the popup "Press OK to redirect to Super admin has no token associated with Alliance trave API provider". User cant interact with its buttons and after a second the page is auto-refreshing.

![archer](https://cloud.githubusercontent.com/assets/13362917/18321768/bddaaac6-752f-11e6-8889-f225b34de11a.png)

Here are the steps that reproduce the problem:
1) Go to https://archer.brandplystaging.com in your browser
2) Enter ZipCode : 84062
3) Log into Brandply site u: superarcher p:1234567
4) Go to Visit Site
5) Click on the archer banner

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#474
