### ISSUE TITLE
Brandply footer too large on iOS 8.4 iPhone

### ISSUE THREAD

**Issue by brandplysreese** [Brandply/publicissues#2]
the black Brandply footer takes up 1/3 of the screen on my iPhone when browsing coupons...see attached.
![img_1891](https://cloud.githubusercontent.com/assets/13644426/9067445/b895f28a-3a9a-11e5-84c6-dd47aff11924.png)

**Comment by pfelsted** [comment]
duplicate it was fixed in M6
