### ISSUE TITLE
default search field text not going away

### ISSUE THREAD

**Issue by pfelsted** [Brandply/publicissues#20]
We need to try and reproduce and add more details.
Customer: Levine Shosh iheartmedia

Simple little one --- but one ae brought up that when you search in the in the search bar, when you tap your finger to it and starts typing, it doesn’t delete the word “search term”- could this be done?

**Comment by brandplysreese** [comment]
I have been un able to reproduce this bug. Ive tested all search inputs on chrome in mac osx and mobile safari and chrome mobile. I havent seen an input the has "search term".

**Comment by pfelsted** [comment]
Ashley was going to try and reach out to the client to reproduce this.

**Comment by pfelsted** [comment]
not reproducable
