### ISSUE TITLE
Filter window is not hiding after clicking on the sort button

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#209]
Platform: Windows - Windows 10
Browser: Firefox
URL of page: https://brandpldev.com
Organization or Member Login
User: archer
Password: 1234567

Description of the problem:
Clicking on the Sort button in Filter window is not hiding it.

Here are the steps that reproduce the problem:
1) Go to https://brandplydev.com in your Firefox browser
2) Enter ZipCode : 84062
3) Log into Brandply site u: superarcher p:1234567
4) Click on filter in the top right corner of the site, set random parameters and click on Sort button.

![brandply](https://cloud.githubusercontent.com/assets/13362917/19000293/186e5d42-8742-11e6-97d3-cd15d90995b2.png)

**Comment by inqueez** [comment]
let's discuss it, I am not sure that with a new UI it should be hidden after click the "sort" button
