### ISSUE TITLE
Enter button not working on ZipCode window

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#21]
Platform: Pc Windows 10
 Browser: Microsoft Edge
 URL of page: https://archer.brandplydev.com/
 Organization or Member Login
 User: archer
 Password: 1234567
 Description of Problem: 

After entering ZipCode on Geolocalization window and pressing Enter buton on keyboard nothing is happening, to accept ZipCode i need to click on Submit buton.

Here are the steps that reproduce the problem:
1) Go to arche.brandlydev.com in your browser
2) Enter ZipCode when prompted: 84062
3) Hit "Enter" button on keyboard

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply1-1#109
