### ISSUE TITLE
Opening offer by search tooltip shows offer for wrong location and  broken Find Deals in Your Area! functionality

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#211]
Platform: Windows - Windows 10
Browser: Firefox, Crhome
URL of page: 
https://brandply.com, https://archer.brandply.com,
https://brandplystaging.com, https://archer.brandplystaging.com,
https://brandplydev.com, https://archer.brandplydev.com

Organization or Member Login
username: superarcher
password: 1234567

Description of the problem:
After setting default ZipCode as 84026 then typing "Sonic" in search tooltip and choosing first or second link (under the Locations name), the page will always open offer for 80210 or 73026 location.
Typing 84026 (or any other ZipCode) in "Find Deals in Your Area!" is not showing offers related to that input.

![finddeals](https://cloud.githubusercontent.com/assets/13362917/19086178/64517aae-8a6d-11e6-9044-f14cdeb78a17.png)

Here are the steps that reproduce the problem:
1) Go to one of urls posted above.
2) Enter ZipCode: 84062
3) Log into site u: superarcher p:1234567
4) Type Sonic in search window and click on first or second link under the "Locations" name
5) Enter ZipCode in Find Deals in Your Area! window: 84062 or any other.
6) Check if offer for 84026 Pleasant Groove location is displayed.

**Comment by pfelsted** [comment]
Duplicate #555
