### ISSUE TITLE
Wrong alert format when redirecting to Travel as not associated user

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#213]
Platform: Windows - Windows 10, Windows 8.1
Browser: Firefox, Chrome
URL of page: https://brandpldev.com
Organization or Member Login
u: superarcher
p: 1234567

Description of the problem:

When clicking on Travel link as superarcher, there is popup with alert "Press OK to redirect to fasle", and OK, Cancel buttons. Clicking on OK is opening new tab with brandplydev main site. I belive there should be just a OK button which will close the popup and information that specified user is not associated with travel site. 

![travel](https://cloud.githubusercontent.com/assets/13362917/19245113/b690b0b2-8f1f-11e6-941c-3e51d9c75493.png)

Here are the steps that reproduce the problem:
1) Go to https://brandplydev.com in your browser
2) Log into site u: superarcher, p: 1234567
3) Open Main Categories and click on Travel link

**Comment by pfelsted** [comment]
Eugene has resovled this on dev branch but not with new ui.
