### ISSUE TITLE
Main Categories dropdown displays all subcategories when open on mobiles

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#222]
Platform: Android, IOS
Browser: Chrome, Firefox
URL of page: https://brandply.com, https://brandplystaging.com, https://brandplydev.com,
u: superarcher
p: 1234567

Description of the problem:
Subcategories should be hide on Main Categories, right now they are displayed under every main category.

![categories](https://cloud.githubusercontent.com/assets/13362917/20061693/339c8652-a501-11e6-96e6-1cab3a036f67.png)

**Comment by inqueez** [comment]
This issue was moved to Brandply/brandply#505
