### ISSUE TITLE
Most of the offers are missing from the site

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#223]
Platform: Windows 10
Browser: Chrome
URL of page: https://brandpldev.com
u: superarcher
p: 1234567

Description of the problem:
Site is displaing only few offers

Here are steps to reproduce the problem

Go to https://brandplydev.com in you browser
Enter Zipcode : 84026
Log into site u: superarcher, p: 1234567
Open Main Categories pick Dining & Food and check offers displayed (there is only one displayed when searaching for 8402 code)

**Comment by inqueez** [comment]
This issue was moved to Brandply/brandply#510

**Comment by inqueez** [comment]
The steps to reproduce are not complete, but an issue has been fixed.
Testing request: https://github.com/Brandply/QA/issues/3
