### ISSUE TITLE
Search display is cut on Firefox browser

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#224]
Platform: Windows 10
Browser: Firefox
URL of page: https://brandpldev.com
u: superarcher
p: 1234567

![search](https://cloud.githubusercontent.com/assets/13362917/20350412/1b773350-ac0f-11e6-93b6-d9efc4dde002.png)

**Comment by inqueez** [comment]
This issue was moved to Brandply/brandply#513
