### ISSUE TITLE
Filter button issue on Firefox

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#225]
Platform: Windows 10
Browser: Firefox
URL of page: https://brandpldev.com
u: superarcher
p: 1234567

Description of the problem:

Clicking on filter button is not opening it.
This issue is hapening only on 1920x1080 resolution set on and 120% zoom on Firefox browser.

Here are steps to reproduce the problem

Go to https://brandplydev.com in you browser
1) Set you screen resolution to 1920x1080
2) Open brandplydev.com on you Firefox browser
3) Set zoom level to 120%
4) Log into site u:superarcher p:1234567
5) On main site click on filter button.

**Comment by inqueez** [comment]
This issue was moved to Brandply/brandply#512
