### ISSUE TITLE
Filter "Reset Sort" button is disabling the sliders functionality 

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#229]
Platform: Windows 10
Browser: Firefox, Chrome
URL of page: https://brandply.com, https://brandplydev.com
u: superarcher
p: 1234567

Description of the problem:

After clicking on the "Reset Sort" button on the filter the Sliders are no longer updating its parameters while setting them on different positions. After doing sort in that situation the sliders settings are not working.

![distance](https://cloud.githubusercontent.com/assets/13362917/20765895/86ecccdc-b734-11e6-8f18-ce4363a8b92f.png)

There are steps to reproduce the problem:

1) Log into Brandply site "https://brandply.com/" u: superarcher, p:1234567
2) Click on Filter button in the top right corner
3) Move sliders (for example Distance) to see if displayed miles are updating
4) Click on Reset Sort button
5) Move sliders again and see if display status is updating

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#527
