### ISSUE TITLE
The Merchants tab is not working

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#23]
Platform: Pc Windows 10
 Browser: Microsoft Edge
 URL of page: https://archer.brandplydev.com/
 Organization or Member Login
 User: archer
 Password: 1234567
 Description of Problem: 

When trying to open Merchants tab the displayed content is blank

The problem seems to appear on Microsoft Edge browser (it was working there before)
but it works fine on Google Chrome browser at the same time.

Here are the steps that reproduce the problem:

 1) Go to arche.brandlydev.com in your browser
2) Log into Archer site
3) Click on Visit Page
4) Open Merchants window - the content is blank

**Comment by pfelsted** [comment]
This was because the API was down.
