### ISSUE TITLE
Buttons to switch the offer view from list to pictures are missing on the dev server

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#230]
Platform: Windows 10
Browser: Chrome, Firefox
URL of page: https://brandpldev.com, https://archer.brandpldev.com
u: superarcher
p: 1234567

Description of the problem:
The buttons to switch offers display between pictures and list are missing on the dev.

![offerview](https://cloud.githubusercontent.com/assets/13362917/20887397/a2e6a858-bafa-11e6-8375-ae2aedcaabc2.png)

**Comment by inqueez** [comment]
This issue was moved to Brandply/brandply#533
