### ISSUE TITLE
Android / IOS - location popup is prompting two times

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#233]
Platform:  Android / IOS (Browserstack)
Devices: Galaxy S7, Galaxy S6, Galaxy S5, iPhone 6S Plus, iPhone 6S, iPhone 6 Plus
Browser: Chrome
URL of page: https://brandply.com
Organization or Member Login
User: superarcher
Password: 1234567

Description of the problem:

After clicking on "Don't Allow" at popup that is asking if to allow user's autolocation, setting zip code manually and login into page the popup is prompting again.

![localization](https://cloud.githubusercontent.com/assets/13362917/21550623/a4f1f26a-cdfb-11e6-9c22-6dcb69c97430.png)
![localization2](https://cloud.githubusercontent.com/assets/13362917/21550626/a67999b2-cdfb-11e6-9eac-ca2f29985697.png)

Here are the steps that reproduce the problem :

1) Go to https://brandply.com in your mobile phone (or choose one from browserstack)
2) When localization popup prompt's click on "Don't Allow"
3) Enter ZipCode when prompted: 84062
4) Log into Brandply site u: superarcher p:1234567
5) Check if popup is showing

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#556
