### ISSUE TITLE
Android - The Store is displaying Deals in the wrong order

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#234]
Platform: Android 
Devices: Galaxy S7 (Browserstack), Galaxy S6 (Browserstack), Galaxy S5
Browser: Chrome
URL of page: https://brandply.com
Organization or Member Login
User: superarcher
Password: 1234567

Description of the problem:
Choosing Store type of offer from search window is displaying the Deal related to the current Zip Code at second place instead of first.

![android](https://cloud.githubusercontent.com/assets/13362917/21551982/b4f78d20-cdfe-11e6-8511-25f7b4dbf873.png)

The problem is occuring with other Stores which contain multiple offers.

Here are steps to reproduce : 
1) Go into http://brandply.com on your Android phone
2) Enter ZipCode : 84062
3) Log into site u: superarcher p: 1234567
4) Type "Sonic" in search window and choose first link (under the "STORES" category)
5) Scroll down to Deals and check if first offer is displayed for 84062 Pleasant Groove location
6) Enter ZipCode in "Find Deals in Your Area" window : "84062" and check first offer again

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#555
