### ISSUE TITLE
Add Organization Admin Dropdown improvement

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#235]
The Admin Dropdown on Add Organization panel contains lot of unsorted data. Please sort it alphabetically.  

![admin dropdown](https://cloud.githubusercontent.com/assets/13362917/21568058/89e40eb6-ceb1-11e6-9a31-f114ddf677be.png)

**Comment by brandplysreese** [comment]
Please make all drop downs and table columns default sort alphabetically and or ascending. Please also add the ability to click a table column header to sort the table, some of the new ui tables have the ability and some dont.

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#554
