### ISSUE TITLE
Please add the Search window filters to the following dropdowns

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#236]
Right now there is only one dropdown using Search window to filter data, which is on the Create User panel.

![add user](https://cloud.githubusercontent.com/assets/13362917/21568273/76916de8-ceb3-11e6-9b00-b52bce8d0117.png)

Please add same functionality to these dropdowns:

1.
Admin Dashboard > Organizations > Edit Member IDs
![memberids](https://cloud.githubusercontent.com/assets/13362917/21568327/f25fa5de-ceb3-11e6-94a0-edcf09af45e2.png)

2.
Admin Dashboard > Organizations > Notifications Report
![notificationsreport](https://cloud.githubusercontent.com/assets/13362917/21568368/3413fa98-ceb4-11e6-8854-ce05fe82f37d.png)

3.
Admin Dashboard > Organizations > Email Notifications
![emailnotifications](https://cloud.githubusercontent.com/assets/13362917/21568387/5da70990-ceb4-11e6-9c9c-a2b9aaa2978e.png)

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#553
