### ISSUE TITLE
The "More Offers from this merchant" fields are not displayed correctly

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#25]
Platform: Pc Windows 10
 Browser: Microsoft Edge
 URL of page: https://archer.brandplydev.com/
 Organization or Member Login
 User: archer
 Password: 1234567
 Description of Problem: 

The "More Offers from this merchant" fields
are not displayed correctly (it seems like there are
always displayed Local offers not related with
actual choosen Merchant ). 

To do this test PC autolocation need to be turned off,
what allows to compare offers from different locations.

Here are the steps that reproduce the problem:

1) Go to arche.brandlydev.com in your browser
2) Enter ZipCode when prompted : 84062
3) Log into Archer site : u: archer p:1234567
4) Click on Visit Page
5) Enter ZipCode when prompted : 84062
6) Open Merchants window
7) Open Club W and check "More Offers from this merchant" fields 
7.1) Open Applebee's and check "More Offers from this merchant" fields
7.2) Open Zipcar and check "More Offers from this merchant" fields
8) Refresh Page
9) Enter ZipCode when prompted : 9862
10) Open Merchants window
11) Open 3 different Merchants offers and compare the 
"More Offers from this merchant" fields

Adding screenshots with 3 different merchants:

<img width="1251" alt="merchants" src="https://cloud.githubusercontent.com/assets/13362917/9327537/dae30e88-45a1-11e5-8930-f2d47e7b9883.png">

**Comment by pfelsted** [comment]
Needs some screen shots

**Comment by pfelsted** [comment]
This issue was moved to Brandply/brandply1-1#121
