### ISSUE TITLE
Issue with search filter visibility

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#26]
Platform: Pc Windows 10
 Browser: Microsoft Edge
 URL of page: https://archer.brandplydev.com/
 Organization or Member Login
 User: archer
 Password: 1234567
 Description of Problem: 

The search filter dynamic data covers values
on starting data
Here are the steps that reproduce the problem:

1) Go to arche.brandlydev.com in your browser
2) Log into Archer site
3) Click on Visit Page
4) Click on Sort option
5) Move slider from left to right and watch if dynamic data covers basic one

Screen:
<img width="263" alt="image" src="https://cloud.githubusercontent.com/assets/13362917/9197653/6a9261b2-4036-11e5-950a-006a6e183536.png">

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply1-1#108
