### ISSUE TITLE
Category and Offer view display mode is resetting to grid after page refresh

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#261]
Platform: Windows 10
Browser: Chrome
URL of page: https://brandplydev.com
Organization or Member Login
User: superarcher
Password: 1234567

Description of the problem:
After switching the Category or Offer view display to list mode, and refreshing page or processing inside page by clicking on links the display setup is resetting to default (grid display)

![viewdisplay](https://cloud.githubusercontent.com/assets/13362917/22038811/c84cf826-dcfc-11e6-80c2-229e5acf4fdb.png)

Here are steps to reproduce the problem:

1) Go into http://brandplydev.com on your browser
2) Log into site u: superarcher p: 1234567
3) Click on Category and Offer view list button (marked on screenshot above)
4) Refresh page or click on category to process inside page
5) Check if Category / Offer view buttons are marked and working as they should for list mode.

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#577
