### ISSUE TITLE
Test Email Notification is not working

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#262]
Platform: Windows 10
Browser: Chrome
URL of page: https://brandplydev.com
Organization or Member Login
User: superarcher
Password: 1234567

Description of the problem:
While entering the correct user email in Test Email Notification option and clicking on Test button, email is not sending and there is no message about error.

![testemail](https://cloud.githubusercontent.com/assets/13362917/22159371/cc7b5b68-df40-11e6-8e3e-8713f1ea04bc.png)

Here are steps to reproduce the problem:

1) Go into http://brandply.com on your browser
2) Log into site u: superarcher p:1234567
3) Click on Admin Dashboard
4) Open Settings > Email Notifications
5) Scroll down to Test Email Notification panel and enter email : pfrdom@gmail.com
6) Choose  Organization Content : Brandply Dev
7) Click on Test button

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#583
