### ISSUE TITLE
admin allowing username to not be email

### ISSUE THREAD

**Issue by aaronrbond** [Brandply/publicissues#264]
In the admin section, when someone creates a user, i am allowed to change the username to be a not email address, but then i am unsuccessful to change back to email address, and the session is in continuous loading.

STEP 1: creating user
![screen shot 2017-02-06 at 11 52 18 am](https://cloud.githubusercontent.com/assets/737596/22658632/d31bc518-ec68-11e6-8636-0969195d7e8e.png)

STEP 2: changing username, successful
![screen shot 2017-02-06 at 12 27 07 pm](https://cloud.githubusercontent.com/assets/737596/22658641/d81fca3c-ec68-11e6-8e3d-6d67539e33a4.png)

STEP 3: you can see that the username is not an email address anymore
![screen shot 2017-02-06 at 12 27 15 pm](https://cloud.githubusercontent.com/assets/737596/22658650/dca2d2ac-ec68-11e6-9603-ceeced908bdc.png)

STEP 4: When i hit submit, it gets caught in forever loading and i can not do anything unless i refresh page and the username is still 'abondtestcode'
![screen shot 2017-02-06 at 12 27 29 pm](https://cloud.githubusercontent.com/assets/737596/22658654/dfec6928-ec68-11e6-8a04-dbb07cec828f.png)

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#600
