### ISSUE TITLE
New created orgs don't show reserved used codes

### ISSUE THREAD

**Issue by aaronrbond** [Brandply/publicissues#269]
## Expected Behavior *

Reserving a code shows users in the reserved used tab in the org admin

## Current Behavior *

no users shown under reserved used tab

## Steps to Reproduce (for bugs) *

1. added 2 codes
2. added 2 reserved codes on org url "testorg"
3. redeemed 1 code
4. shows one reserved available, but no reserved used

![screen shot 2017-02-08 at 2 56 45 pm](https://cloud.githubusercontent.com/assets/737596/22754877/011efbcc-ee0f-11e6-8c69-5d30b1ef5509.png)
![screen shot 2017-02-08 at 2 50 41 pm](https://cloud.githubusercontent.com/assets/737596/22754685/69b6f4a6-ee0e-11e6-94d9-410f552a3e9e.png)
![screen shot 2017-02-08 at 2 50 45 pm](https://cloud.githubusercontent.com/assets/737596/22754688/6cdb98da-ee0e-11e6-87ee-48d6f1b85d76.png)

## Context

when you reserve a code on a newly created orginazation should list them under the 'reserved used' tab

## Your Environment *

* User Info: aaronrbond
* Server Environment (e.g. dev staging prod): production
* Browser: chrome 52.0
* Operating System and version (desktop or mobile): macosx 10.12.2
* Relevant Links: testorg.brandply.com org

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#614
