### ISSUE TITLE
Issue with Merchants name rarely displayed as blank URL

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#28]
Platform: Pc Windows 10
 Browser: Microsoft Edge
 URL of page: https://archer.brandplydev.com/
 Organization or Member Login
 User: archer
 Password: 1234567
 Description of Problem: 

Issue for Microsoft Edge

Merchants name on upper left corner of 
Merchant view is displayed on Microsoft Edge browser
as blank URL link (seems to happen very rarely
I found 3 cases on many tests) the same
Merchants names are not displayed as URL
for Google Chrome

Here are the steps that reproduce the problem:

1) Go to arche.brandlydev.com in your browser
2) Log into Archer site
3) Click on Visit Page
4) Open Merchants tab
5) Open 1-800-BASKETS and check upper left corner 
5.1) Open 1-800-FLOWERS.COM and check upper left corner
5.2) Open 1-800-GOT-JUNK? and check upper left corner
6) Repeat all steps for Google Chrome and compare names

Screen:
<img width="709" alt="image" src="https://cloud.githubusercontent.com/assets/13362917/9198320/909cb60a-403b-11e5-928a-44b4f345d96b.png">

**Comment by pfelsted** [comment]
This is a problem with Skype recognizing this a s a phone number and adding a link.. Its a browser plugin.
