### ISSUE TITLE
Website offers are not working

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#29]
Platform: Pc Windows 10
Browser: Microsoft Edge
URL of page: https://archer.brandplydev.com/
Organization or Member Login
User: archer
Password: 1234567
Description of Problem:

Whole site seems to have no offers. The local and popular offers fields are empty, also Main Categories
content is changed

Screen:

![image](https://cloud.githubusercontent.com/assets/13362917/9220849/c7235ef4-40e5-11e5-9c51-367f5e6b3272.png)

**Comment by pfelsted** [comment]
This was fixed this morning
