### ISSUE TITLE
Problem with Main Categories tab on Iphone 6

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#38]
Platform: IOS
Device: Iphone 6
URL of page: https://archer.brandply.com/
Organization or Member Login
User: PFR2
Password: 1234567
Description of Problem:

The Main Categories window is not displayed on screen.
It can be open by clicking on blank space in one spot
Screen:
<img width="592" alt="ios" src="https://cloud.githubusercontent.com/assets/13362917/9331610/b8a775e2-45c0-11e5-810d-c4634c41ec25.png">

**Comment by pfelsted** [comment]
This issue was moved to Brandply/brandply1-1#124
