### ISSUE TITLE
How To Use / FAQ / Privacy Policy are not displayed on IOS

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#39]
Platform: IOS
Device: Iphone 6 / Iphone 6 Plus
URL of page: https://archer.brandply.com/
Organization or Member Login
User: PFR2
Password: 1234567
Description of Problem:

The dynamic field with How To Use, FAQ and Privacy Policy buttons is not displaing on the IOS.

This is screen with missing content made on windows browser:
<img width="585" alt="ios missing content" src="https://cloud.githubusercontent.com/assets/13362917/9357827/4cc8dc7a-4689-11e5-9113-c7c6866ae3aa.png">

**Comment by pfelsted** [comment]
This issue was moved to Brandply/brandply1-1#125
