### ISSUE TITLE
Remember Me  Saving login name

### ISSUE THREAD

**Issue by nhat8888** [Brandply/publicissues#4]
LOGIN screen doesn't remember the last name I used to log in (maybe the Remember me button isn't working).   Attached is a screen showing that it brought up Hudson  (which is not the login I have used).  Not sure where it is pulling that name up from.  I used nhat user name and it always comes up with Hudson.

![image](https://cloud.githubusercontent.com/assets/13439850/9073220/d6f0008a-3acd-11e5-8f87-2dab009237db.png)

**Comment by brandplysreese** [comment]
Remember me function not working. 

Details
Platform: Mac OSX Yosemite
Browser: Chrome
URL of page(s): https://archer.brandplydev.com/
Organization or Member Login
User: sarcher
Password (only add passwords of test accounts): 1234567

Description:
Clicking the checkbox next to "remember me" while logging in should make it so the user doesnt have to type their username every time they come back to the site and log in. It should auto populate the input based on a cookie.

Screenshots or screen casts of Issue:
https://www.dropbox.com/s/40yb8nhswi9ome3/Screen%20Capture%202015-08-10%20at%2019.24.57.mov?dl=0

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply1-1#99
