### ISSUE TITLE
The Main Categories panel is not hiding on IOS when choosing a category

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#40]
Platform: IOS
Browser: Iphone, Iphone Plus
URL of page: https://archer.brandply.com/
Organization or Member Login
User: PFR2
Password: 1234567
Description of Problem:

When selecting a category on IOS the Main Categories window remains open, what decreasing
visibility on site.

Here are the steps that reproduce the problem:
1) Go to archer.brandply.com in your browser
2) Enter ZipCode when prompted: 84062
3) Log into Archer site u:PFR2 p:1234567
4) Open Main Categories and choose one.

Screenshot of problem:
<img width="502" alt="ios golf" src="https://cloud.githubusercontent.com/assets/13362917/9359220/69fffa9c-4690-11e5-8f27-16c55a43d4ed.png">

**Comment by pfelsted** [comment]
This issue was moved to Brandply/brandply1-1#126
