### ISSUE TITLE
Mapping Correct Merchant Locations

### ISSUE THREAD

**Issue by AshleyBeresh** [Brandply/publicissues#41]
The location that is pinned on the map on the brandply.com site for specific offers shows it in a different location from where it is actually at on google maps & the merchants website but the physical address is the same on all pages.

URL of page(s): Here is one example for Salsaritas: https://alliedinsmgr.brandply.com/offer/14243729

Description of Issue (steps to reproduce): Screenshots or screen casts of Issue:

Address/Map brandply.com site:
![screen shot 2015-08-19 at 2 09 01 pm](https://cloud.githubusercontent.com/assets/13679167/9364981/f5c5c3f4-467c-11e5-81b4-1cd7bde01cda.png)
![screen shot 2015-08-19 at 2 09 09 pm](https://cloud.githubusercontent.com/assets/13679167/9364985/0018f56a-467d-11e5-9c04-6673a09b5c33.png)

Address on Google Maps:
![screen shot 2015-08-19 at 2 09 43 pm](https://cloud.githubusercontent.com/assets/13679167/9364992/095bcc6a-467d-11e5-8714-e9396a825651.png)

Address/Map on Merchant Website:
![screen shot 2015-08-19 at 2 09 56 pm](https://cloud.githubusercontent.com/assets/13679167/9364999/15b876a2-467d-11e5-99cc-6d66c91b3834.png)

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply1-1#120
