### ISSUE TITLE
Problem with editing stars colour on the offers

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#42]
Platform: Tested on Windows 10 and IOS
Browser: Chrome, Edge  IPhone & IPad (Safari)
URL of page: https://archer.brandply.com/
Organization or Member Login
User: PFR2
Password: 1234567
Description of Problem:

The stars displayed near offers are not editable from red back to gray untill the offer is opened.

Here are the steps that reproduce the problem:
1) Go to archer.brandply.com in your browser
2) Enter ZipCode when prompted: 84062
3) Log into Archer site u:PFR2 p:1234567
4) Open Local (mark gray star as red, cant unmark it back on Local page)
5) Open marked offer then switch star back to gray.

Screenshots of problem:

<img width="577" alt="star edit problem" src="https://cloud.githubusercontent.com/assets/13362917/9382415/e392052a-4740-11e5-81e8-5a74ab799130.png">
<img width="575" alt="star color problems" src="https://cloud.githubusercontent.com/assets/13362917/9382416/e43f3fec-4740-11e5-84bb-c24166ad478c.png">

**Comment by pfelsted** [comment]
This issue was moved to Brandply/brandply1-1#127
