### ISSUE TITLE
Main Categories are not displayed in alphabetical order on Chrome

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#43]
Platform: Windows 10, Android
Browser: Google Chrome
URL of page: https://archer.brandply.com/
Organization or Member Login
User: PFR2
Password: 1234567
Description of Problem:

Health & Beauty category is displayed before other categories, rest is sorted in alphabetical order.
Problem appears on Google Chrome browsers.

Here are the steps that reproduce the problem:
1) Go to archer.brandply.com in your browser
2) Enter ZipCode when prompted: 84062
3) Log into Archer site u:PFR2 p:1234567
4) Open Main Categories in Google Chrome and Internet Explorer and compare the display order.

<img width="406" alt="categories order" src="https://cloud.githubusercontent.com/assets/13362917/9386462/e24172c6-475b-11e5-9469-3a2875f49cf6.png">

**Comment by pfelsted** [comment]
This issue was moved to Brandply/brandply1-1#128
