### ISSUE TITLE
Phone number link on IOS is not working 

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#44]
Platform: IOS - IPad, IPad Plus, IPad Air
Browser: Safari
URL of page: https://archer.brandply.com/
Organization or Member Login
User: PFR2
Password: 1234567
Description of Problem:

Phone number link displayed on the offer should open number ready to call on the platform.

Here are the steps that reproduce the problem:
1) Go to archer.brandply.com in your browser
2) Enter ZipCode when prompted: 84062
3) Log into Archer site u:PFR2 p:1234567
4) Open Main Categories and select Golf
5) Open Cedar Hills Golf Club
6) Click on Phone Number

There are some screens for different devices:

IPad, IPad Plus, IPad Air
<img width="236" alt="phone ios" src="https://cloud.githubusercontent.com/assets/13362917/9405010/724abe20-47f4-11e5-95b0-dd60ce8c9f36.png">

IPad Mini
<img width="276" alt="ipad mini" src="https://cloud.githubusercontent.com/assets/13362917/9405087/04153b5a-47f5-11e5-8ea9-3723a067f2a9.png">

How it works on Android (Galaxy S5)
<img width="474" alt="galaxy s5" src="https://cloud.githubusercontent.com/assets/13362917/9405038/a2fe4406-47f4-11e5-8406-33343f3214b4.png">

**Comment by pfelsted** [comment]
This issue was moved to Brandply/brandply1-1#134
