### ISSUE TITLE
Main Categories subclasses are not displayed on Samsung Tab

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#45]
Platform: Android, Samsung Tab 4 10.1
Browser: Chrome
URL of page: https://archer.brandply.com/
Organization or Member Login
User: PFR2
Password: 1234567
Description of Problem:

Main Categories Classes are not showing subclasses after tapping on them

Here are the steps that reproduce the problem:
1) Go to archer.brandply.com in your browser
2) Enter ZipCode when prompted: 84062
3) Log into Archer site u:PFR2 p:1234567
4) Open Main Categories and select any type
5) Check if additional field with sublcasses is showing up

Screen made on Samsung Tab:
<img width="498" alt="tab" src="https://cloud.githubusercontent.com/assets/13362917/9410738/21a93a86-4822-11e5-88e4-ea76e60cb009.png">

Screen made on working version (Windows)
<img width="420" alt="windows" src="https://cloud.githubusercontent.com/assets/13362917/9410754/3df87062-4822-11e5-9ff6-8d7c06e04774.png">

**Comment by pfelsted** [comment]
This issue was moved to Brandply/brandply1-1#133
