### ISSUE TITLE
Favorites mispelled

### ISSUE THREAD

**Issue by AshleyBeresh** [Brandply/publicissues#46]
"Favorites" is mispelled on the tab below. This was found under alliedinsmgr.brandply.com when you are viewing "deal history" under a particular user.

![screen shot 2015-08-21 at 1 56 20 pm](https://cloud.githubusercontent.com/assets/13679167/9415277/1c35e52e-480c-11e5-86e8-5833cf59497e.png)

**Comment by pfelsted** [comment]
This issue was moved to Brandply/brandply1-1#132
