### ISSUE TITLE
Reedem Coupon stuck on loading

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#47]
Platform: Android, Windows, IOS
Browser: Chrome, Safari
URL of page: https://archer.brandply.com/
Organization or Member Login
User: PFR2
Password: 1234567
Description of Problem:

When clicking on Reedem Coupon under Reedem Via instore, Reedem Via instore print or Reedem Via link, the page is stuck on loading untill error message prompt up.

Here are the steps that reproduce the problem:
1) Go to archer.brandply.com in your browser
2) Enter ZipCode when prompted: 84062
3) Log into Archer site u:PFR2 p:1234567
4) Go to Local and open Sonic offer
5) Choose one reedem option.

<img width="354" alt="reedem coupons" src="https://cloud.githubusercontent.com/assets/13362917/9437972/aa4ecb96-4a5a-11e5-914a-b25343463d90.png">

**Comment by pfelsted** [comment]
This appears to be working now
