### ISSUE TITLE
Samsung Tab 4 - Fields opening when clicking in wrong place

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#48]
Platform: Android, Samsung Tab 4 10.1
Browser: Chrome
URL of page: https://archer.brandply.com/
Organization or Member Login
User: PFR2
Password: 1234567
Description of Problem:

After clicking under Main Categories / Merchants/ Local/ Popular/ Archerindurstires.com / Sort
fields in specific area, the page process like these fields were actually clicked.  

Here are the steps that reproduce the problem:
1) Go to archer.brandply.com in your browser
2) Enter ZipCode when prompted: 84062
3) Log into Archer site u:PFR2 p:1234567
4) Click on fields
 marked as white rectangles on the screenshot below.
<img width="613" alt="tab 4" src="https://cloud.githubusercontent.com/assets/13362917/9439460/86b36b30-4a67-11e5-8c8f-dcad1fa92bb6.png">

**Comment by pfelsted** [comment]
This issue was moved to Brandply/brandply1-1#131
