### ISSUE TITLE
Website is not working on Samsung Note and Samsung Tab 2

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#49]
Platform: Android, Samsung Note 10.1, Samsung Tab 2 10.1
Browser: Chrome
URL of page: https://archer.brandply.com/
Organization or Member Login
User: PFR2
Password: 1234567
Description of problem:

The page is not displayed correctly on Samsung Note 10.1, Samsung Tab 2 10.1

<img width="431" alt="asd" src="https://cloud.githubusercontent.com/assets/13362917/9440723/7ee5bce6-4a71-11e5-8da1-044e6782e039.png">

**Comment by pfelsted** [comment]
This issue was moved to Brandply/brandply1-1#130
