### ISSUE TITLE
Repeating Geolocation petition

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#5]
Platform: Pc Windows 10
Browser: Microsoft Edge
URL of page:  https://archer.brandplydev.com/
Organization or Member Login
User: archer
Password: 1234567
Description of Problem: 

After setting manually ZipCode location and loggin in, then loggin out web site is asking me again to set location.

Here are the steps that reproduce the problem:
![image](https://cloud.githubusercontent.com/assets/13362917/9119584/aa2350b0-3c77-11e5-8742-d4ff43c618cf.png)

**Comment by esperanzaua** [comment]
Short Description (Title): Forgot Password

Details


Platform: Windows XP 
Browser: Mozilla Firefox
URL of page(s):  https://archer.brandplydev.com/
Organization or Member Login
User: archer
Password: 1234567

Description of Issue:
"Restore your password" link page don't lead user to the respect result.

Steps to reproduce:
1. In Login screen click "Forgot password" > bug - "Login" screen covering "Restore your password" link page. only after click "Login" screen hidden.
2. Entering valid username > click "Submit" > bug - lead to the begining of "Restore your password" link page and asking "Enter your account username" again .
3. No option to restore password by e-mail or no function to restore account if forgot username

Screenshots or screen casts of Issue:
![fp_1](https://cloud.githubusercontent.com/assets/13663282/9134906/5b158ca0-3d11-11e5-9b5a-203ce01ac255.gif)
