### ISSUE TITLE
After opening new page with coupon the location window pops up on loading

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#55]
Platform: Windows
Browser: Chrome, Edge
URL of page: https://archer.brandply.com/
Organization or Member Login
User: PFR2
Password: 1234567
Description of Problem:

When clicking on Reedem Coupon the localization window is prompting up untill coupon is loaded.

Here are the steps that reproduce the problem:
1) Go to archer.brandply.com in your browser
2) Enter ZipCode when prompted: 84062
3) Log into Archer site u:PFR2 p:1234567
4) Go to Local and open Sonic offer
5) Reedem coupon.

**Comment by brandplysreese** [comment]
test again on milestone 10

**Comment by pfr1990** [comment]
Works well
