### ISSUE TITLE
The Enter ZipCode button is redirecting to home page

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#56]
Platform: Windows
Browser: Chrome, Edge
URL of page: https://archer.brandply.com/
Organization or Member Login
User: PFR2
Password: 1234567
Description of Problem:

After clicking on Enter ZipCode button the site is redirecting to home page.
To do this test turn off pc autolocation

Here are the steps that reproduce the problem:
1) Go to archer.brandply.com in your browser
2) Enter ZipCode when prompted: 84062
3) Log into Archer site u:PFR2 p:1234567
4) After ZipCode window prompts up close it
4) Go to Local and click on Enter ZipCode button

**Comment by brandplysreese** [comment]
Try to reproduce in milestone 10

**Comment by pfr1990** [comment]
Works well
