### ISSUE TITLE
Load More button stuck on loading for Popular Offers

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#58]
Platform: Windows XP, Windows 8, Windows 8.1, Windows 10
Browser: Chrome, Edge, IE11, Firefox
URL of page: https://archer.brandply.com/
Organization or Member Login
User: PFR2
Password: 1234567
Description of Problem:

Problem seems to appear only with ZipCode set manually

The Load More button on the Popular Offers in header stuck on loading.
Problem still appears after reseting cache.

Here are the steps that reproduce the problem:
1) Go to archer.brandply.com in your browser
2) Enter ZipCode when prompted: 84062
3) Log into Archer site u:PFR2 p:1234567 or as admin
4) Scroll down to Popular Offers and hit on Load More button

<img width="839" alt="asd" src="https://cloud.githubusercontent.com/assets/13362917/9611582/bf138d78-50e0-11e5-858e-539bccf87b7e.png">

**Comment by pfelsted** [comment]
This issue was moved to Brandply/brandply1-1#147
