### ISSUE TITLE
Geolocation window seems to have unlimited space

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#6]
Platform: PC Windows 10
Browser: Microsoft Edge
URL of page: https://archer.brandplydev.com/
Organization or Member Login
User: archer
Password: 1234567
Description of Problem:

After Geolocation window showed up I tried to enter maximal amount of characters but it seems like it have unlimited space

Here are the steps that reproduce the problem:
![image](https://cloud.githubusercontent.com/assets/13362917/9120665/ceaf77f0-3c7d-11e5-97fd-2be3bf973771.png)

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply1-1#115
