### ISSUE TITLE
Cant edit stars displayed on offers in the Local Offers view

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#64]
Platform: Windows
Browser: Chrome, Edge
URL of page: https://archer.brandply.com/
Organization or Member Login
User: PFR2
Password: 1234567
Description of Problem:

Offers displayed from Main Categories or Popular enable to edit stars from gray to red and from red to gray.
Offers from Local view enable only to edit from gray to red.

Here are the steps that reproduce the problem:
1) Go to archer.brandply.com in your browser
2) Enter ZipCode when prompted: 84062
3) Log into Archer site u:superarcher p:1234567
3) Open Visit Site and and open Local Offers
4) Choose an offer with red star and try to change colour back to gray

**Comment by brandplysreese** [comment]
Test again on milestone 10

**Comment by pfr1990** [comment]
Works well

**Comment by pfr1990** [comment]
After switching star colors on Local in Chrome and refreshing page the changes are displayed but on IE, Firefox and Edge stars are colored for yellow instead of gray or colors are not changed after refreshing
