### ISSUE TITLE
Remove Popular Offers from Homepage

### ISSUE THREAD

**Issue by AshleyBeresh** [Brandply/publicissues#65]
Please remove "popular offers" from the homepage of all organizations. 

Users are getting confused what the difference between "popular" and "local" offers are. When they login and see offers that are not location based within the "popular" section, they think something is working incorrectly on the platform. We should only have them access "Popular offers" if clicking in the top navigation. When there are "featured offers" specific to the organization they should default to where "popular" current sits but if there are not "featured offers" we should have it removed from the homepage and only show "local". 

Platform: All

Screen shot of what should be removed from homepage:
![screen shot 2015-09-03 at 11 15 57 am](https://cloud.githubusercontent.com/assets/13679167/9662502/acd73986-522d-11e5-89fa-ad14ca6f0d13.png)

Screen shot of where "popular" offers should only be accessed in the nav bar:
![screen shot 2015-09-03 at 11 16 04 am](https://cloud.githubusercontent.com/assets/13679167/9662524/cbc7c5c2-522d-11e5-9c83-2fc944b9aab3.png)

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply1-1#150
