### ISSUE TITLE
Unnecessary reedem link on Restaurant.com offer page

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#66]
Platform: Windows, OSX
Browser: Chrome, Safari
URL of page: https://archer.brandply.com/
Organization or Member Login
User: PFR2
Password: 1234567
Description of Problem:

All Restaurant.com offers with reedem via link option have additional hyperlink address displayed under telephone number, other randomly tested offers with reedem via link feautre dont display hiperlink so it might be issue only for Restaurant.com offers or appears randomly.

Here are the steps that reproduce the problem:
1) Go to archer.brandply.com in your browser
2) Enter ZipCode when prompted: 84062
3) Log into Archer site u:superarcher p:1234567
3) Open Visit Site and and open Local Offers
4) Open Restaurant.com offer

<img width="831" alt="bez tytulu" src="https://cloud.githubusercontent.com/assets/13362917/9733648/5940108c-562d-11e5-81e0-5c75f4557c72.png">

**Comment by brandplysreese** [comment]
Going to leave this as is.
