### ISSUE TITLE
Issue with Display of Sam's Club Offer

### ISSUE THREAD

**Issue by pfelsted** [Brandply/publicissues#7]
Details
Platform: PC Windows 7
Browswer: Chrome
URL of page: https://archer.brandplydev.com/
Organization or Member Login
User: archer
Password: 1234567
Description of Problem
The offer for Sam's Club has the Category display wrong.  It appears to be displaying it twice.  Also there is text that is white in the background of the offer.  See image.

Screenshots of Problem:
![image](https://cloud.githubusercontent.com/assets/13591900/9122300/5b8c3c50-3c45-11e5-82b8-df4d8994c6a8.png)

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply1-1#114
