### ISSUE TITLE
User search in Admin Panel

### ISSUE THREAD

**Issue by AshleyBeresh** [Brandply/publicissues#88]
For super admins on brandply.com — When searching for particular users who have signed up under a organization within the admin panel, you cannot search by anything other than user name and email address. It would be helpful to additional be able to search by organization. 

Screen shot is an example showing that when I searched for the organization "allied" it only pulled up those who have signed up with "allied" in their username or email address:
![screen shot 2015-09-21 at 11 28 01 am](https://cloud.githubusercontent.com/assets/13679167/9996065/4d396204-6053-11e5-9153-0e751f945f42.png)

Screen shot shows how many have actually signed up under "allied" on their actual organization's website:
![screen shot 2015-09-21 at 11 28 10 am](https://cloud.githubusercontent.com/assets/13679167/9996087/6fc78ad0-6053-11e5-82b4-137c2ff7d0a6.png)

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#173
