### ISSUE TITLE
Switch left main nav icon for mobile

### ISSUE THREAD

**Issue by AshleyBeresh** [Brandply/publicissues#89]
Having two main navigation buttons on the mobile app gets confusing. We should add something to the "account" button (lefthand side nav button) to differentiate between the two. 

Screenshot of current mobile navigations:
![img_2792](https://cloud.githubusercontent.com/assets/13679167/9998776/d5e95106-6060-11e5-9118-b24a51917976.PNG)

Our thought is to use an icon of a profile like the screen shot below:
![screen_shot_2015-09-21_at_12 54 06_pm](https://cloud.githubusercontent.com/assets/13679167/9998675/6452f9de-6060-11e5-8ce4-9d504956cf5e.png)

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#172
