### ISSUE TITLE
Feature: And agreement to Terms and Use to Signup Page

### ISSUE THREAD

**Issue by pfelsted** [Brandply/publicissues#9]
Add a check box and the phrase "I agree to the Terms of Use of this site."  (This phrase needs to be approved by Erik.  Also the Terms of Use should be linked and show as a link (different color) that creates a popup (<div> - that does not leave the page) that shows the Terms of Use (the text for the terms of use will be added by Erik).  The text for terms of sevice must be stored in the DB with a version number and a date when added because it will change over time.  

The user can not click "Register" until they click the I agree check box.  When they do check this and press register we need to store the date they agreed and the version of the Terms of Use that was agreed to and the IP address of the request.  This agreement information needs to be in a separate table from the user since we will have users agree to different terms(as the terms change) but we need historical mechanism to show when they agreed to which terms version.  We also need a mechanism on the user that indicates that we need to ask the user to agree to new terms (like a bit field indicating if they have agreed to terms or not).  This allows us to clear the bit and force users to reagree to new terms.  I will create another issue for handling existing users and changing of terms.

![image](https://cloud.githubusercontent.com/assets/13591900/9125894/f2ed6e6c-3c62-11e5-9762-617aed011613.png)

**Comment by felster10** [comment]
"I have read and agree to the Terms and Privacy Policy for use of this site."

Terms and Privacy Policy must be a live link to each of those documents....live link on the website footer - not too small clearly visible.

I will provide the legal document/info early next week.

**Comment by pfelsted** [comment]
This issue was moved to Brandply/brandply1-1#135
