### ISSUE TITLE
Merchant Ad Signup added to admin section

### ISSUE THREAD

**Issue by AshleyBeresh** [Brandply/publicissues#91]
We currently have an online form that merchants can fill out and submit to our team when they want coupons added to the entire Access platform. We then send this info to Access' merchant team to add. We want to streamline this process and add it as a feature in our admin section so merchants easily access and can fill out the info when needed. We would then forward this info on when we received an email that a request has been made for a new ad/offer to be placed. 

Our current form/information requested:
http://form.jotform.us/form/50296023150141

We would need an additional field added that can expand when merchants are larger and have several different locations that the offers will be accepted at. Also, it would be nice if google maps could recognize the business location and auto populate the fields when typing.

**Comment by pfelsted** [comment]
Need to ask Amy and Stu to see if we still need this.
