### ISSUE TITLE
Local Offers display 2 same offers for each zipcode

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#96]
Platform: All
Browser: All
URL of page: https://brandplystaging.com/
Organization or Member Login
User: superarcher
Password: 1234567
Description of Problem:

Site is displaying two same offers for each ZipCode entered in Local.

Here are the steps that reproduce the problem:
1) Go to brandplystaging.com in your browser
2) Log into Archer site u:superarcher p:1234567
3) Go to Local
4) Enter random ZipCodes: 02200, 77777, 12345
5) There should be always two offers from screenshot below

<img width="730" alt="random offers" src="https://cloud.githubusercontent.com/assets/13362917/12196574/e1fb3de8-b5ff-11e5-8a65-841609f6ef3b.png">

**Comment by brandplysreese** [comment]
moved to brandply
